### ISSUE TITLE
Difference between google/google-api-ruby-client and google-cloud-ruby

### ISSUE THREAD

**Issue by mustela** [GoogleCloudPlatform/google-cloud-ruby#1009]
Hey everyone, I'm starting an integration with Google Vision, and I realized that there are 2 libs from Google that supports it, this one and this one: https://github.com/google/google-api-ruby-client. 

Wondering which is the difference and which one is the recommended one? 

Thanks

**Comment by quartzmo** [comment]
Hi @mustela,

I am an open-source contributor to this library, so do not consider this an official answer from Google, but here is my own explanation which may help you decide.

Unlike `google-api-ruby-client`, which is a generated library that provides support for [a wide range of Google APIs](https://developers.google.com/api-client-library/ruby/apis/), this library has been hand-written in order to feel natural and comfortable to Rubyists. Doing this takes care and time, and so we can't hope to cover all Google APIs, but Cloud Vision is one of the APIs that was chosen.

Here is an example using the [`google-cloud-vision` gem](https://rubygems.org/gems/google-cloud-vision) from this library:

```ruby
require "google/cloud/vision"

vision = Google::Cloud::Vision.new

image = vision.image "path/to/face.jpg"

face = image.face

face.features.to_h.count #=> 9
face.features.eyes.left.pupil
#=> #<Landmark (x: 190.41544, y: 84.4557, z: -1.3682901)>
face.features.chin.center
#=> #<Landmark (x: 233.21977, y: 189.47475, z: 19.487228)>
```

I looked around for a similar example that uses `google-api-ruby-client`, and I think [this is a good one](https://github.com/mcdickenson/google-vision-example/blob/master/dog_food_client.rb).

Does this answer your question? Thanks for asking it.

**Comment by mustela** [comment]
Thanks @quartzmo! Those are good details. And it's true that I would use `google-cloud-vision` instead of the other one since it "feels" better, but do you know if there is plan to support other APIs like Drive for instance? Since the lack of this API would force me use the other one to not have 2 different ways to connect to the Google services. 

Thanks

**Comment by quartzmo** [comment]
I don't think Drive will be supported by this library anytime soon, but of course I don't know the future, so I'm not absolutely certain of that.

I hope you will try this library for Cloud Vision, even if you need to use `google-api-ruby-client` for Drive. In addition to the "feel" (by which I really mean, a clear and concise API, boosting productivity), @blowmage and I worked hard on the [documentation and examples](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-vision/v0.21.1/google/cloud/vision) as well as conveniences for authentication (depending on your environment.) We also recently upgraded it to use gRPC for the transport layer (while I believe `google-api-ruby-client` still uses the Rest API), so you may get a performance win as well.

**Comment by mustela** [comment]
Thanks for your time, this was really useful!
