### ISSUE TITLE
creating partitioned tables via the api

### ISSUE THREAD

**Issue by kcore** [GoogleCloudPlatform/google-cloud-ruby#1061]
I tried searching in the repo as well but couldn't find any documentation or even source to create/handle partitioned tables. Am I missing something here OR is this not yet supported? If yes any ETA on the same?

**Comment by blowmage** [comment]
Hi @kcore, thanks for opening this issue. Unfortunately table partitioning is marked "experimental, and the current policy is not to add features/options that are marked `[Experimental]`., like BigQuery Dataset location, in order to avoid having to deprecate and remove them if they are discontinued. That said, we already support reading the value, as you noted, which is now inconsistent.

**Comment by blowmage** [comment]
Hi @kcore, thanks for opening this issue. Unfortunately table partitioning is marked `[Experimental]`, and the current policy is not to add features/options that are marked experimental. This is because those features can change, or be removed completely. There are other BigQuery features also marked experimental that we also are unable to support yet.

**Comment by kcore** [comment]
got it. thanks @blowmage appreciate the quick response
