### ISSUE TITLE
Can't run db:migrate after adding stackdriver gem

### ISSUE THREAD

**Issue by thagomizer** [GoogleCloudPlatform/google-cloud-ruby#1095]
Repro:
1. Add stackdriver gem to the gem file of a project using App Engine Flex and Cloud SQL
2. run RAILS_ENV=production bundle exec rake db:migrate to migrate the database before deploying

Result:
Unable to initialize Google::Cloud::Logging with empty project_id

Expected:
To be able to migrate my cloud sql instance.

Notes
gcloud init and gcloud auth login had already been run. gcloud app deploy was working.

**Comment by quartzmo** [comment]
@thagomizer Thank you for finding this!

@dazuma @hxiong388 I added the `stackdriver` label, but based on the error (`Unable to initialize Google::Cloud::Logging with empty project_id`), should this be considered just a Logging issue?

**Comment by hxiong388** [comment]
Yeah, I think having both logging and stackdriver labels are appropriate.

**Comment by hxiong388** [comment]
Ok, seems like this output is just a warning message coming from [railtie](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/ba0ebae7abf78c46fde61b8d8c687a5afd7e23ed/google-cloud-logging/lib/google/cloud/logging/rails.rb#L114-L115). It wouldn't have interrupted the db:migrate task.

The reason why the google-cloud-logging railtie prints warning message is because the default Rails logger isn't initialized yet, so it can't print failure message to Rails log like [google-cloud-error_reporting railtie](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/ba0ebae7abf78c46fde61b8d8c687a5afd7e23ed/google-cloud-logging/lib/google/cloud/logging/rails.rb#L114-L115) does.

I think here are our options:
1. Keep it this way.
2. Remove the warning messages because it's the lesser evil of the two.
3. Improve the warning message like "Unable to initialize Google::Cloud::Logging with empty project_id; fall back to default logger"
4. Move the google-cloud-logger railtie to initialize after Rails Logger is initialized, so we can print warning message into Rails Logger if necessary. But this is a bigger change may have other implication I'm not aware of.

I'm gonna investigate option 4 a little bit to see if it has any negative side effect. @thagomizer please let me know which option you think is most reasonable.

**Comment by hxiong388** [comment]
After reading the [Rails source code](https://github.com/rails/rails/blob/92703a9ea5d8b96f30e0b706b801c9185ef14f0e/railties/lib/rails/application/bootstrap.rb#L32-L59), I think it's a bad idea to tamper with logger after Rails Logger has been initialized, because then we have to reset logging level with that ActiveSupport logic.

I'm now more inclined for option 3. @thagomizer does that work for you?

**Comment by hxiong388** [comment]
closed via #1151
