### ISSUE TITLE
Low-level classes are displaying in the sidebar navigation of the documentation (Datastore::V1 and Logging::V2)

### ISSUE THREAD

**Issue by remi** [GoogleCloudPlatform/google-cloud-ruby#1141]
The sidebar navigation is showing new top-level headings for [`Datastore::V1`](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.23.0/google/cloud/datastore/v1/datastoreclient) and [`Logging::V2`](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.23.0/google/cloud/logging/v2/loggingservicev2client)

![screen shot 2016-12-14 at 10 45 26 pm](https://cloud.githubusercontent.com/assets/280/21214355/1482bdac-c24f-11e6-914b-ca7ef3590d4f.png)

If a user navigates to these pages (like I did), they will not find useful overviews of the client libraries for these services (like all of the other nav links show).

Instead, these display some of the internals of the gem that shouldn't be linked to from the top-level nav.

![screen shot 2016-12-14 at 10 49 15 pm](https://cloud.githubusercontent.com/assets/280/21214462/b60ba558-c24f-11e6-8ad8-96a97637d19a.png)

![screen shot 2016-12-14 at 10 49 35 pm](https://cloud.githubusercontent.com/assets/280/21214465/b99549e0-c24f-11e6-934a-06c8e7f87453.png)

**Comment by blowmage** [comment]
The documenting of the low-level API was intentional. This is one of the conditions for the library reaching 1.0. The issue outlining the inclusion is GoogleCloudPlatform/gcloud-common#207, but the current navigation structure is slightly different to workaround some inflexibility in the angular app.

FWIW, I agree that this is likely confusing to users. We have tried to minimize the confusion on the GCP GitHub UI, but it is likely even more confusing when viewing the documentation elsewhere. For example, on [rubydoc.info](http://www.rubydoc.info/gems/google-cloud-datastore) the documentation for 1) the Google Cloud library code, 2) the GAPIC code, and 3) the protobuf code, are all shown side-by-side with no way to differentiate what is the public API and what is the low-level API.

![datastore-nav](https://cloud.githubusercontent.com/assets/730/21231976/56430744-c2a7-11e6-91ee-bc5bab643973.png)

When a user searches for "Entity" they are shown both the Google Cloud class and the protobuf class. Which one do they use? How do they tell them apart?

![datastore-search](https://cloud.githubusercontent.com/assets/730/21231988/60148eb4-c2a7-11e6-8b71-7e4d03711da0.png)

In the current documentation/packaging approach there is no way to differentiate between these three well-defined and distinct code boundaries. The user will not know which one to use unless they are well versed in the Google toolchain. IMO this has the potential to be detrimental to the efforts made to improve the onboarding process for developers switching to the Google Cloud library.

**Comment by swcloud** [comment]
Adding @omaray.

The current github doc site does not seem to implement the design we intended. For example. "Datastore V1" should be a level below 'Datastore' and should be displayed as just 'V1'. Also the data types such as 'Duration' and 'Timestamp' should not show up in the left navigation panel. They should be just listed on a single page which is loaded by a single item on the left navigation panel called 'Data Types'.

**Comment by swcloud** [comment]
Regarding the rubydoc.info site: Google::Cloud::Datastore::Entity is a veneer-level class, which happens to have the same name of GRPC-level class Google::Datastore::V1::Entity. They have different name space hence they are differentiated by being displayed in the different places on the navigation hierarchy on the left side. IMO, it is self-explainable to the developers. That's why the concept of 'name space' exists in the first place.

**Comment by blowmage** [comment]
> The current github doc site does not seem to implement the design we intended. For example. "Datastore V1" should be a level below 'Datastore' and should be displayed as just 'V1'.

Correct. This is due to the inflexibility of the angular app mentioned earlier.

> Also the data types such as 'Duration' and 'Timestamp' should not show up in the left navigation panel. They should be just listed on a single page which is loaded by a single item on the left navigation panel called 'Data Types'.

Also correct. See the "known issues" on #1117.

**Comment by quartzmo** [comment]
Moving these nav items to a deeper level depends on a fix for GoogleCloudPlatform/google-cloud-ruby#1141.

Will that alone close this issue? Or is there something else to consider?

**Comment by remi** [comment]
> The current github doc site does not seem to implement the design we intended. For example. "Datastore V1" should be a level below 'Datastore' and should be displayed as just 'V1'.
> ...
> Regarding the rubydoc.info site: Google::Cloud::Datastore::Entity is a veneer-level class, which happens to have the same name of GRPC-level class Google::Datastore::V1::Entity

@swcloud Can you help me understand why the gRPC representation of `Entity` should show up in the documentation at all?

As a developer who has used Datastore using different client libraries and written/published some of our google-cloud-datastore samples, I actually find the presence of two `Entity` classes to be confusing, myself.

I filed this issue because, when I saw "Datastore::V1" last night, I thought it was a bug 😕 

On cloud.google.com, Google Cloud Datastore has *wonderful* docs IMO, eg. [Entities, Properties, and Keys](https://cloud.google.com/datastore/docs/concepts/entities) and [Datastore Queries](https://cloud.google.com/datastore/docs/concepts/queries).  These pages do not mention specific versions of the API, however, so I'm curious why we want to display this to end-users on the docs hosted on the GitHub UI?

**Comment by swcloud** [comment]
@remi My understanding is that we want to give developers an option from which they can directly call the vkit layer (gapic/grpc).

@omaray can explain more regarding the intention on this.

**Comment by quartzmo** [comment]
I am currently working on a PR to add a deeper level of nesting to the left nav (GoogleCloudPlatform/gcloud-common#209).
