### ISSUE TITLE
Broken link to "Core" appears in the sidebar navigation of the documentation

### ISSUE THREAD

**Issue by remi** [GoogleCloudPlatform/google-cloud-ruby#1142]
![screen shot 2016-12-14 at 10 53 59 pm](https://cloud.githubusercontent.com/assets/280/21214561/4888b416-c250-11e6-86d0-53949bcb79d2.png)

**Comment by blowmage** [comment]
I noticed this as well. #1143 will fix this, but we can fix it in a more direct way by labeling that module with `@private`.

**Comment by blowmage** [comment]
I agree, Core shouldn't be public. I think it used to be labeled "Errors" and showed all the shared error classes.

**Comment by quartzmo** [comment]
@blowmage You are saying that the error types in core *should* be public, and the nav item should read "Errors", correct?

**Comment by blowmage** [comment]
The error classes are part of the public API, so it would be good to have them documented somewhere. I _thought_ that they were documented before, but I think you would know better than I.

**Comment by quartzmo** [comment]
Honestly I can't remember what happened. On Oct 31, I added Core to the google-cloud TOC in [this commit](https://github.com/GoogleCloudPlatform/google-cloud-ruby/commit/e0afea0233659cdc0fe233304758c2c49f548420). I believe Core (with error types being the public members) must remain public. The issue here is that Core docs are not currently copied into the `google-cloud` docs. And, the TOC listing for Core can be improved to list all error types. I'll work on a PR for this issue.

**Comment by quartzmo** [comment]
Reopening, pending some work on the TOC and possibly also the Angular site app to activate the 'Core' nav item and display the sub nav containing the error subclasses.
