### ISSUE TITLE
Cloud Speech Ruby Veneer: @private Methods not marked a private

### ISSUE THREAD

**Issue by pbogle** [GoogleCloudPlatform/google-cloud-ruby#1208]
Several methods are documented as @private in the comment but not actually marked private in the ruby source code, should they be?  E.g. https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-speech/lib/google/cloud/speech/stream.rb#L265

**Comment by blowmage** [comment]
These methods are documented correctly. The `@private` directive is used by YARD to indicate that the method is not part of the public API. It does not describe the method level of access. This is used because ruby does not have the notion of package-level access, so these methods need to be `public`, even though they are not part of the public API. These methods can change in future versions without breaking backwards compatibility.

**Comment by quartzmo** [comment]
@pbogle Hope this is satisfactory, please reopen if not.

**Comment by pbogle** [comment]
Thanks for the explanation, sounds good.
