### ISSUE TITLE
Links to classes are broken in Monitoring documentation

### ISSUE THREAD

**Issue by remi** [GoogleCloudPlatform/google-cloud-ruby#1217]
Steps to reproduce:

 1. Visit [Google Cloud documentation](https://googlecloudplatform.github.io/google-cloud-ruby)
 2. Browse to [Monitoring > V3 > MetricServiceClient #create_metric_descriptor](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.24.0/google/cloud/monitoring/v3/metricserviceclient?method=create_metric_descriptor-instance)
 3. Click on the return type [`Google::Api::MetricDescriptor`](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.24.0/google/api/metricdescriptor) to see the class documentation

Expected result:

 - The documentation for `Google::Api::MetricDescriptor` is shown

Actual result:

 - 404 Not Found

![screen shot 2017-02-02 at 3 20 57 pm](https://cloud.githubusercontent.com/assets/280/22572892/3a609db8-e95b-11e6-9a99-4b8ca9654a35.png)

**Comment by quartzmo** [comment]
@remi Thanks for reporting this. I suspect we can generalize this issue, as it will probably be true for any linked type that does not have a namespace that includes the service name (in this case, `monitoring`). 

This should only be a problem in the `google-cloud` package docs, because they are created by copying docs from the individual packages. In the `google-cloud-monitoring` docs, the page for [google/api/metricdescriptor](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-monitoring/v0.22.0/google/api/metricdescriptor) is present.

**Comment by blowmage** [comment]
I can confirm the class documentation is defined in [google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/api/metric.rb](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/api/metric.rb#L128). Agree this looks to be a problem with the umbrella packaging... _le sigh_

**Comment by bjwatson** [comment]
@quartzmo Can you verify whether this affects the ML or GA candidate APIs? If so, we need to raise the priority of this issue.

**Comment by blowmage** [comment]
To be clear, this affects only the [GCP hosted documentation](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs), and does not affect the user's local documentation or documentation [hosted elsewhere](http://www.rubydoc.info/gems/google-cloud-datastore).

The documentation application's use of an "umbrella" package has been problematic for us. The approach is basically duplicating documentation. So the same docs are found under `google-cloud-monitoring` that are also found under `google-cloud`. Because of the many issues we have had with this approach I do not believe it is sustainable, and we have proposed GoogleCloudPlatform/gcloud-common#218 as a way to link to navigation across packages instead of duplicating it.

**Comment by quartzmo** [comment]
@bjwatson I started work on this yesterday and should have the fix complete today. The answer to your question is yes, but I hope to have it closed before you need to change the priority.

**Comment by bjwatson** [comment]
@quartzmo Thanks! But too late to stop me from changing the priority. ;)
