### ISSUE TITLE
Session Pool

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/google-cloud-ruby#1235]
Use a pool to manage sessions. Session creation is expensive and the number of sessions that can be created is limited. Sessions and the pool will be hidden from end users, but the pool behavior can be configured by the following settings:

1. `min`: Minimum number of sessions that the pool will maintain at any point in time.
2. `max`: Maximum number of active sessions that the pool will have at any point in time.
3. `keepalive`: The frequency that the session pool checks for idle sessions and keep them alive. If the number of idle sessions is more than `min` then they can be closed and culled from the pool.

Creating transactions with `BeginTransaction` is an expensive call, so some fraction of the pool may preallocate transactions. If this is done, end users should be able to control what percentage of the pool will do this. However, we should investigate if using `TransactionSelector.begin` adds the same amount of overhead that `BeginTransaction` does.

The pool should follow the behavior of other ruby connection pools and raise if there are no sessions available, so end users can handle the error and adjust the pool size if needed/wanted.

**Comment by vkedia** [comment]
As for calling `BeginTransaction` it is useful since because it allows one to make concurrent read/query calls. Otherwise you would have to wait for the first read/query to yield the first chunk before you can make any subsequent calls. Also if the first read failed for whatever reason you will not get back the transaction id.
