### ISSUE TITLE
Support Pub/Sub streaming pull?

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/google-cloud-ruby#1287]
The protobuf/GAPIC layer defines the ability to pull messages with a stream, instead of paging responses. Do we want to support streaming on pull requests?

**Comment by bjwatson** [comment]
@garrettjonesgoogle Can you answer this question?

**Comment by garrettjonesgoogle** [comment]
We do want to support it and actually make it the primary way of getting messages from Pub/Sub long-term because it is more performant. This should be hidden in the implementation though, such that the user doesn't have to know if a synchronous pull or asynchronous streaming is used under the hood. This implies that the surface should operate with a callback model.

For the moment the server method doesn't work.

**Comment by bjwatson** [comment]
Should this be considered release blocking for Beta, or is it more of an implementation detail?

**Comment by garrettjonesgoogle** [comment]
I think that depends on the surface in Ruby. When support is added, will users have to change their code? If not, then it shouldn't block beta.

**Comment by bjwatson** [comment]
Thanks, @garrettjonesgoogle.

What do you think, @blowmage?

**Comment by blowmage** [comment]
This looks additive to me. I think we should retain backwards compatibility.

**Comment by bjwatson** [comment]
Great! `P2+` it remains.

**Comment by blowmage** [comment]
I imagine we would just replace the internals of [`Subscription#listen`](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-pubsub/v0.23.1/google/cloud/pubsub/subscription?method=listen-instance) to use the stream.

**Comment by blowmage** [comment]
@garrettjonesgoogle On March 1 you said:

> For the moment the server method doesn't work.

Is streaming pull working now?

**Comment by garrettjonesgoogle** [comment]
Not yet.

**Comment by blowmage** [comment]
K, thx!

**Comment by blowmage** [comment]
Support for the streaming API has been added to master, awaiting release.
