### ISSUE TITLE
Support Service Account for Translation?

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/google-cloud-ruby#1345]
It seems like Service Account should be supported with the Translation API. For instance in Python: https://github.com/GoogleCloudPlatform/google-cloud-python/pull/2731

@jonparrott : can you confirm?

**Comment by jonparrott** [comment]
Yes, it should

**Comment by quartzmo** [comment]
Once Service Account support is working, should API key support be removed?

**Comment by blowmage** [comment]
Looks like the python lib has [removed API key](https://github.com/GoogleCloudPlatform/google-cloud-python/pull/2823/files) support.

**Comment by blowmage** [comment]
I looked at the implementation again, and it turns out we have already implemented support for service accounts last November. (issue: #1046, pr: #1050)

@omaray @jonparrott Currently we support both service accounts and API keys. Python has removed support for API keys. Should we do the same? Or should we maintain both modes of authentication?

**Comment by omaray** [comment]
Per the conversation with the API team, we should keep both (and thanks for checking and confirming).
