### ISSUE TITLE
Cloud Storage integration testing (local, CI, etc.)

### ISSUE THREAD

**Issue by ababich** [GoogleCloudPlatform/google-cloud-ruby#1363]
Good day!

I cannot find any solution how to automate testing of integration my code with Cloud Storage.

I imagine some Cloud Storage auth mode like `local` which will work in test (and may be dev) environment of application and simulate API but operate with objects in `./tmp` or [even better] in memory.

The idea is to allow CI and other automated testing w/o touching actual `Cloud Storage`

Total stubbing like in `google-cloud-ruby` gem tests doesn't look workable for client applications. Can you please point out if there are some solutions.

Thanks!

**Comment by blowmage** [comment]
Generally, I recommend creating an application entity that is responsible for the functionality you want to expose in your application, and then mock that. For example, you could create a FileStorage store that is backed by GCS in production, but backed by an in-memory cache during tests. That way you only mock what you own. 

Mocking at the API layer like we do is not generally a good approach, but was somewhat necessary to ensure the library is correct. I think that is more due to the difference between library testing and application testing.

**Comment by ababich** [comment]
I agree, so the fact is that there is no existing solution for the API wrapper I noticed and you've described.

Thanks for confirmation! Just didn't want to reinvent the wheel

**Comment by blowmage** [comment]
No problem. Thanks for the question!
