### ISSUE TITLE
clarification on handling auth/access to storage from GKE

### ISSUE THREAD

**Issue by pdougall1** [GoogleCloudPlatform/google-cloud-ruby#1386]
It is not clear what is meant by "we handle authentication for you with no configuration" interms of implementation.  Does this mean the environment variables are already present and ready to use?
```
        Google::Cloud::Storage.new(
          project: ENV['GOOGLE_CLOUD_PROJECT'],
          keyfile: File.absolute_path(ENV['GOOGLE_CLOUD_KEYFILE'])
        )
```

or that the library will access them directly from the environment so they do not need to be passed in?
```
Google::Cloud::Storage.new()
```

**Comment by quartzmo** [comment]
@pdougall1 Thanks for asking this question! And the answer is yes, for sure! It's covered in more detail in [AUTHENTICATION.md](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/AUTHENTICATION.md).

**Comment by hxiong388** [comment]
@pdougall1 FYI the [Compute Engine](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/AUTHENTICATION.md#compute-engine) section from authentication guide also applies to Google App Engine and Google Container Engine. If your application is running from any one of the three Google Cloud Platform environments, you won't need to pass in `project_id` and `keyfile`, unless you wish to override the default authentication. The code can just be: 
```ruby
Google::Cloud::Storage.new()
```
@quartzmo Maybe we can update the auth documentation to mention "Google Cloud Platform environments" instead of just "Compute Engine". I can imagine some users might not realize Google App Engine and Google Container Engine run on top of Google Compute Engine.

**Comment by quartzmo** [comment]
@hxiong388 I will do that as part of resolving this issue. Good suggestion!

@pdougall1 Can you suggest locations in the docs where this should be discussed, and isn't, so that I can add better coverage?

**Comment by quartzmo** [comment]
Is this related to #1803?

**Comment by hxiong388** [comment]
@quartzmo I don't think so. The config mechanism discussed in #1803 is for non-GCP environments, where auth info needs to be provided, one way or another. Versus this issue is about clarifying auth self-discovering on GCP environments.

**Comment by pdougall1** [comment]
Wow I'm sorry I haven't been paying attention to this!  I just got the notification that it was closed, but I never saw that it was answered!  

Thanks for putting work in!  Sorry I was silent!  Things look great!
