### ISSUE TITLE
Missing quality level for Stackdriver Trace(Google Cloud Trace)

### ISSUE THREAD

**Issue by premist** [GoogleCloudPlatform/google-cloud-ruby#1407]
It seems like README.md misses quality level indication for Stackdriver Trace. Is it intentionally missing?

**Comment by hxiong388** [comment]
@premist Stackdriver Trace, Stackdriver Error Reporting, Stackdriver Debugger, and Stackdriver Monitoring are all currently in Alpha quality level.

They are intentionally left out from the top level README.md, because they are somewhat different from the rest of the libraries in this repo. We will add in these documentation soon when we figure out the best documentation strategy.

**Comment by premist** [comment]
Thanks for explanation!
