### ISSUE TITLE
Links to source code of methods on protobuf types are broken

### ISSUE THREAD

**Issue by remi** [GoogleCloudPlatform/google-cloud-ruby#1423]
Example: docs for [Google::Monitoring::V3::TimeInterval
](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.28.0/google/monitoring/v3/timeinterval)

![screen shot 2017-04-13 at 1 35 56 am](https://cloud.githubusercontent.com/assets/280/24996921/9417ecfc-1fe9-11e7-9525-101e221509e2.png)

^--- Source Code link broken

Broken link: https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/google-cloud/master/google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/common.rb#L49

Or all of the Source Code links on google/api types like: [Google::Api::Metric](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.28.0/google/api/metric) or common types like [Google::Protobuf::Timestamp](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.28.0/google/protobuf/timestamp)

**Comment by blowmage** [comment]
This is only an issue for the umbrella package. One more reason to link to the package docs IMHO.

**Comment by blowmage** [comment]
The correct link is:

https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/common.rb#L49

**Comment by blowmage** [comment]
Unfortunately, all those links will be to the dummy documentation files, and not show any code, because so much of these GAPIC methods are created at runtime.

**Comment by quartzmo** [comment]
This behavior is unfortunately present for all types' source links (not just GAPIC) in the `google-cloud` meta-package docs.

In `google-cloud`'s [`Google::Cloud::Bigquery::Project`](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.28.0/google/cloud/bigquery/project), all source code links return 404, since they link to a path (`google-cloud-ruby/blob/google-cloud/master/google-cloud-bigquery/`) that does not exist in the meta-package's source directory.

In `google-cloud-bigquery`'s [`Google::Cloud::Bigquery::Project`](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-bigquery/v0.26.0/google/cloud/bigquery/project), the source code links work correctly.

There is probably a one-off workaround for this, but it is yet another example of the difficulty of implementing meta-package docs as copies of member package docs, rather than as simply references to member package docs.

**Comment by quartzmo** [comment]
Moved to the public [planning wiki](wiki/Planning) due to the delay in implementing the new documentation site.
