### ISSUE TITLE
Monitoring Docs example for MetricServiceClient#list_time_series returns an error

### ISSUE THREAD

**Issue by thagomizer** [GoogleCloudPlatform/google-cloud-ruby#1474]
The example for list_time_series doesn't create a valid TimeInterval so if you copy and paste the code you get an error.

**Comment by geigerj** [comment]
Configuring the initialization values for the variables in all the samples is outside the scope of the GAPIC team but, per offline discussion, assigning to myself to configure a single method as a proof-of-concept of how this will be done.

**Comment by geigerj** [comment]
I did look into this and made an external doc demonstrating how to initialize these values. I'll leave this open until I've moved the example to the external `googleapis/googleapis` repo.

@omaray is now working on the general problem of how to do this for all GAPIC samples that need configuration.

**Comment by blowmage** [comment]
@geigerj Have the docs been moved to the `googleapis/googleapis` repo yet? Can this issue be closed?

**Comment by geigerj** [comment]
@blowmage No. The GAPIC team is not currently maintaining method sample initialization code. This is essentially the same problem as https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/1866. Since like issues will affect nearly every GAPIC method, I don't think addressing them individually is sustainable. These changes will ultimately come from upstream and not at the google-cloud-ruby level, and I've created https://github.com/googleapis/toolkit/issues/1809 as an uber-issue.
