### ISSUE TITLE
pubsub: acknowleging messages doesn't prevent them from getting pulled again

### ISSUE THREAD

**Issue by dbesserman** [GoogleCloudPlatform/google-cloud-ruby#1514]
I can't figure a way to have the message 'consumed'
After creating a subscription, pulling events from it, then acknowledging those events, I expect those events to be marked. But when I pull the subscription again, it sends me the same results as the first time. Just as if I did not acknowledged those results.
What am I missing ?
Thanks

**Comment by quartzmo** [comment]
@dbesserman This should not be happening, and I'm not sure what the problem is. This project has acceptance tests that run against the live service verifying that once an event is acknowledged, pulling will not return it again. Please take a look at [this test](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-pubsub/acceptance/pubsub/pubsub_test.rb#L229-L239) for example. It is a test of the snapshot feature but if you ignore the seek/snapshot parts, it provides coverage for the behavior in question. Can you share your code?

**Comment by blowmage** [comment]
This appears to be a characteristic of the Google Cloud Pub/Sub service. The [Subscriber Overview](https://cloud.google.com/pubsub/docs/subscriber) states:

> Google Cloud Pub/Sub usually does not redeliver acknowledged messages.

So even assuming that the message was acknowledged within the subscriptions ack deadline, it _may_ be pulled from the subscription again.
