### ISSUE TITLE
Release of the Cloud Speech API v1

### ISSUE THREAD

**Issue by echan00** [GoogleCloudPlatform/google-cloud-ruby#1520]
https://cloud.google.com/speech/release-notes

Should we expect utilization of the google-cloud-speech gem to change based on the new release?

**Comment by blowmage** [comment]
I'm not sure what you were asking here. Are you asking if the gem needs to change to support V1? Or are you asking if we expect total usage of the gem to increase because of the release of V1?

The gem already supports V1. Changes were made in google-cloud-speech 0.24.0 to support V1. You can read the 0.24.0 release notes here:

https://github.com/GoogleCloudPlatform/google-cloud-ruby/releases/tag/google-cloud-speech%2Fv0.24.0

**Comment by echan00** [comment]
I'm asking if the gem needs to change to support V1. Thanks
