### ISSUE TITLE
[Storage] Request to add Bucket#storage_class= to change default storage class

### ISSUE THREAD

**Issue by frankyn** [GoogleCloudPlatform/google-cloud-ruby#1603]
Hi,

This is a request to add `Bucket#storage_class=` to the Storage Client library. 

Expected documented example:
```Ruby
require "google/cloud/storage"

storage = Google::Cloud::Storage.new project: "PROJECT_ID"
bucket = storage.bucket "bucketname"

bucket.storage_class = "NEARLINE"
```

**Comment by quartzmo** [comment]
I don't see that it is currently possible, but it appears that we are now able to add `Bucket#storage_class=`, since `storageClass` is marked writeable in the [Buckets](https://cloud.google.com/storage/docs/json_api/v1/buckets#resource) resource API docs.

@frankyn Would you like to update the title and description for this issue to request it?

**Comment by frankyn** [comment]
I updated the title and description @quartzmo! Thank you!

**Comment by blowmage** [comment]
This looks like another change to the API that we were unaware of. This value used to be set on bucket creation only, but the docs now show that it can be updated.

**Comment by frankyn** [comment]
Thank you both!
