### ISSUE TITLE
BigQuery Dataset does not appear to have :name

### ISSUE THREAD

**Issue by BookOfGreg** [GoogleCloudPlatform/google-cloud-ruby#1612]
Hi team,

I was following the example provided at 
[google-cloud-bigquery-0.26.0/lib/google/cloud/bigquery/dataset/list.rb:80](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-bigquery/lib/google/cloud/bigquery/dataset/list.rb#L80)
And it resulted in an Argument Error as seen in the below block.

```ruby
require "google/cloud/bigquery"
keyfile = 'mykeyfile-token.json'
project = 'my-analytics'

bigquery = Google::Cloud::Bigquery.new(
  project: project,
  keyfile: keyfile
)

bigquery.datasets.all(request_limit: 5) do |dataset|
  puts dataset.name
end

=> ArgumentError: Symbol or String expected, but NilClass given.
```

When I inspect what a dataset is, I can see it does not have a `:name` method on it. Is this an error in documentation, or are there situations where there is no `name` method?

```ruby
[1] pry(#<MyController>)> dataset.class
=> Google::Cloud::Bigquery::Dataset
[2] pry(#<MyController>)> dataset.methods - Object.methods
=> [:delete,
 :name=,
 :description,
 :description=,
 :location,
 :query,
 :service,
 :table,
 :tables,
 :create_table,
 :created_at,
 :modified_at,
 :etag,
 :project_id,
 :service=,
 :query_job,
 :ensure_service!,
 :gapi,
 :dataset_id,
 :default_expiration,
 :default_expiration=,
 :access,
 :dataset_ref,
 :patch_gapi!,
 :ensure_full_data!,
 :api_url,
 :create_view,
 :gapi=,
 :reload_gapi!,
 :data_complete?]
```

**Comment by BookOfGreg** [comment]
Appears in documentation at:
http://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-bigquery/v0.27.1/google/cloud/bigquery
That dataset.dataset_id is the replacement for name. Maybe just old docs. Shall I PR new docs in here?

**Comment by blowmage** [comment]
Hi Greg, thanks for opening the issue. Apologies for the troubles you are having.

Dataset has both [`dataset_id`](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-bigquery/v0.27.1/google/cloud/bigquery/dataset?method=dataset_id-instance) _and_ [`name`](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-bigquery/v0.27.1/google/cloud/bigquery/dataset?method=name-instance). So I think you are running into a different problem. (BTW, `name` can be `nil`.)

Your pry example is not showing `Dataset#name` because of `Object#name`, but it does show `Dataset#name=`.

Can you post the backtrace of the error? I'm curious where that `NilClass` is being given as an argument.

**Comment by BookOfGreg** [comment]
The error came from another gem, coderay. I misdiagnosed this as an issue with calling name.
```
gems/coderay-1.1.1/lib/coderay/helpers/plugin_host.rb:215:in `validate_id'
```
I had placed a pry (the first ruby section) inside another pry (next to the puts in the second ruby section) and coderay is a dependency of pry. This was my mistake in nesting my debuggers.

Sorry for wasting your time on a rookie mistake!

**Comment by blowmage** [comment]
No problem, glad you got it figured out.
