### ISSUE TITLE
Google Cloud `Credentials` classes should subclass `Google::Auth::Credentials`

### ISSUE THREAD

**Issue by geigerj** [GoogleCloudPlatform/google-cloud-ruby#1729]
The new GAPIC surface assumes the `credentials` argument is an instance of `Google::Gax::Credentials`. By having `Google::Cloud::Credentials` subclass `Google::Gax::Credentials`, we can remove some duplicated code and resolve this issue.

(Context: I originally hand-edited the [Spanner autogen](https://github.com/GoogleCloudPlatform/google-cloud-ruby/pull/1727/commits/c439522aec458db7f0853daae9631c1a9584031b) to loosen this assumption. But in general, we don't want autogen code to depend on google-cloud code, since GAX has broader scope than google-cloud-core.)

**Comment by blowmage** [comment]
The problem with this is that it forces a dependency on `google-gax` on to gems that would otherwise not have a dependency on it. Another option is to only change the `Credentials` classes of the gems that already depend on `google-gax` to inherit from `Google::Gax::Credentials` rather than `Google::Cloud::Credentials`.

**Comment by blowmage** [comment]
I'll take this now that Credentials has been added to the googleauth gem.

**Comment by blowmage** [comment]
I believe we should deprecate `Google::Cloud::Credentials`, and change the existing service `Credentials` classes to inherit from `Google::Auth::Credentials` instead. The existing service `Credentials` classes should also remove their `@private` designation and become part of the public API.

**Comment by blowmage** [comment]
Implemented in #1824.
