### ISSUE TITLE
Allow usage of googleauth ~> 0.6 in google-cloud-core

### ISSUE THREAD

**Issue by kappiah** [GoogleCloudPlatform/google-cloud-ruby#1783]
Would it be possible to allow `google-cloud-core` to use `googleauth ~> 0.6`?

This currently results in an unresolvable gemfile if there is a need to use `> 2.0` of the `jwt` gem

**Comment by blowmage** [comment]
Unfortunately it is not as easy as updating the dependency set in the google-cloud-core gem. We are matching the dependency set in the grpc and google-gax gems. So in order to update our dependency we will need new versions of those gems that also update the dependency. 

I hope to see a grpc 1.7.0 and google-gax 0.9.0 release that update their dependency on googleauth.

**Comment by quartzmo** [comment]
This will be addressed by #1804.

**Comment by geigerj** [comment]
Fixed by #1804.
