### ISSUE TITLE
docs on Google::Cloud::Debugger constructor have "project_id", should be "project"

### ISSUE THREAD

**Issue by matti** [GoogleCloudPlatform/google-cloud-ruby#1797]
All README's + https://cloud.google.com/debugger/docs/setup/ruby

vs 
https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-debugger/lib/google/cloud/debugger.rb#L365

**Comment by blowmage** [comment]
@frankyn Is this something you can help with? The code example in the section [Using agent parameters](https://cloud.google.com/debugger/docs/setup/ruby#using_agent_parameters) on the cloud site are incorrectly using `project_id` instead of `project`. The previous code examples are using the Stackdriver configuration approach where the `project_id` argument is correct.

**Comment by frankyn** [comment]
@blowmage, I'll help resolve and update cloud site.

**Comment by blowmage** [comment]
Thanks!

**Comment by frankyn** [comment]
Republished. Closing issue.

**Comment by matti** [comment]
Still multiple project_id’s out there? https://github.com/GoogleCloudPlatform/ruby-docs-samples/blob/master/stackdriver/debugger.ru (linked from the web docs that still also contain project_id) @frankym

**Comment by frankyn** [comment]
Thanks for the follow-up. I'll review, I misunderstood.

**Comment by quartzmo** [comment]
@frankyn Is there anything left to do for this issue? The docs now look correct to me.

**Comment by frankyn** [comment]
@matti I reviewed the client libraries and `project_id` is expected except when using Debugger with `Debugger.new`.

**Comment by matti** [comment]
what about https://cloud.google.com/debugger/docs/setup/ruby

**Comment by blowmage** [comment]
All those examples look correct to me.
