### ISSUE TITLE
Add max_staleness/bounded_staleness to Client#snapshot method

### ISSUE THREAD

**Issue by frankyn** [GoogleCloudPlatform/google-cloud-ruby#1809]
I'm not currently able to define a max_staleness/bounded_staleness when creating a snapshot as a parameter, but [Python](https://googlecloudplatform.github.io/google-cloud-python/latest/spanner/snapshot-api.html) for example does include this parameter in their snapshot method. This parameter is surfaced in the `Client#read` method, and I think it's better understood if surfaced as part of `Client#snapshot` method as well.

The request is to add a parameter for max_staleness/bounded_staleness to the `Client#snapshot` method.

I'm open to interpretation if there's reasons for not adding this parameter to `Client#snapshot`.

**Comment by quartzmo** [comment]
@frankyn Thanks for requesting this. Is this addition urgent for any reason?

**Comment by vkedia** [comment]
Bounded staleness mode is only useful for single use transaction which means users can only do a single read/query with this timestamp. That is the reason it is not added to `Client#snapshot` since users should create that only if they want to do more than one read/query at that snapshot.
Python has it because in Python for both single user and multi use snapshots, one needs to create the snapshot object.

**Comment by quartzmo** [comment]
@vkedia Thank you for this clarification!

**Comment by blowmage** [comment]
Closing as these arguments are not supported on Read/Only transactions.

**Comment by frankyn** [comment]
Thanks @vkedia for the clarification!
