### ISSUE TITLE
[Feature request] Support Cloud KMS

### ISSUE THREAD

**Issue by tragiclifestories** [GoogleCloudPlatform/google-cloud-ruby#1832]
Currently there is no support for Cloud KMS in this client, but it would be useful to my company at least. I will try and find the time to make a PR, but if anyone else has the bandwidth that would be super.

**Comment by quartzmo** [comment]
@tragiclifestories Thank you for this request. I believe Cloud KMS support is on the official roadmap, and that you can expect the PR to come from the maintainers. 

@geigerj  Can you provide any guidance on when we might expect a Cloud KMS package?

**Comment by geigerj** [comment]
Correct, KMS is on the roadmap. We expect to have a library out mid-December.

**Comment by tragiclifestories** [comment]
Excellent, thanks.

**Comment by henrahmagix** [comment]
May we please have an update on expected delivery date for this?

I ask because I need to access the CloudKMS API, and at the moment the only gem I can use is [google-api-ruby-client](https://github.com/google/google-api-ruby-client) [0.10.3](https://github.com/google/google-api-ruby-client/releases/tag/0.10.3), which was released over a year ago (see reason below). My worry is that a 13-month old release of the generated API in google-api-ruby-client may fail before CloudKMS is delivered to this gem, and there won't be an alternative for my case.

Sorry if this is the wrong place to raise my issue; I'm not sure where else to ask about intended support for google-api-ruby-client 0.10.3 (I fear I cannot word such a query in an acceptable way to be a question on the [tagged Stack Overflow](http://stackoverflow.com/questions/tagged/google-api-ruby-client)).

---

Reason: The context is a padrino app in which I cannot install `mime-types >= 3.0`, required by google-api-ruby-client >= 0.11.1, due to [this padrino-mailer commit](https://github.com/padrino/padrino-framework/commit/701fca1c5059bcc3cbea57edb0d92457036307b0))

**Comment by jbolinger** [comment]
@jonparrott do you know what's planned for Cloud KMS?

**Comment by jonparrott** [comment]
Cloud KMS is on the roadmap, however, we do not generally discuss timelines. Once their API is live we can generate a client library relatively quickly, but that is the blocker.

In the meantime, you can continue to use the google-api-ruby-client. It is in maintenance mode and should not experience any significant changes at this point.

**Comment by quartzmo** [comment]
Moving to [wiki/Feature-backlog](https://github.com/GoogleCloudPlatform/google-cloud-ruby/wiki/Feature-backlog) since this request is now more than 180 days old.
