### ISSUE TITLE
undefined method `credentials_with_scope' for Google::Cloud::Trace::Credentials:Class

### ISSUE THREAD

**Issue by jrun** [GoogleCloudPlatform/google-cloud-ruby#1836]
My Rails app produces this error after upgrading to google-cloud-trace 0.28.0:

```
Note: Google::Cloud::Trace is disabled because it failed to authorize with the service. (undefined method `credentials_with_scope' for Google::Cloud::Trace::Credentials:Class)
```

`Google::Cloud::Trace::Railtie` calls `Google::Cloud::Trace::Credentials.credentials_with_scope` which was removed in fbd13ed330fba01c23f4cba93ddcf93aa7253714.

**Comment by blowmage** [comment]
Thank you for opening this issue. I can confirm this is indeed an issue for all `Railtie` classes. I am updating these libraries now and will be deploying new versions for all of them very soon.

**Comment by blowmage** [comment]
The credentials verification bug has been fixed in Railtie for the following gems:

* [Debugger 0.29.1](https://github.com/GoogleCloudPlatform/google-cloud-ruby/releases/tag/google-cloud-debugger%2Fv0.29.1)
* [Error Reporting 0.28.1](https://github.com/GoogleCloudPlatform/google-cloud-ruby/releases/tag/google-cloud-error_reporting%2Fv0.28.1)
* [Logging 1.3.1](https://github.com/GoogleCloudPlatform/google-cloud-ruby/releases/tag/google-cloud-logging%2Fv1.3.1)
* [Trace 0.28.1](https://github.com/GoogleCloudPlatform/google-cloud-ruby/releases/tag/google-cloud-trace%2Fv0.28.1)

Thank you for opening the issue and letting us know of this.
