### ISSUE TITLE
Generated docs for google-cloud-language don't work

### ISSUE THREAD

**Issue by thagomizer** [GoogleCloudPlatform/google-cloud-ruby#1866]
The generated documentation throws a GAX error

```ruby
require "google/cloud/language/v1"

language_service_client = Google::Cloud::Language::V1.new
document = {}
response = language_service_client.analyze_syntax(document)
```
Here's the error
.../google-gax-0.10.2/lib/google/gax/api_callable.rb:351:in `rescue in block in retryable': GaxError Exception occurred in retry method that was not classified as transient, caused by 3:One of content, or gcs_content_uri must be set. (Google::Gax::RetryError)

**Comment by quartzmo** [comment]
@geigerj This is falling outside of SLO, any update?

**Comment by geigerj** [comment]
This was fixed on a local refresh so is likely an upstream configuration issue that has since been fixed. I'll get a refresh out asap.

**Comment by geigerj** [comment]
I miscategorized this issue on the misunderstanding that it referred to the API quickstart, which the GAPIC team has prioritized, rather than the method samples, which are generally unconfigured and a known issue across GAPICs and GAPIC languages. @vchudnov-g is leading the effort to improve sample generation in GAPIC, including for method samples like this one, but unfortunately, currently, we're not generally able to provide customized sample code initialization values at the method level.

**Comment by vchudnov-g** [comment]
While I am working on improving our sample generation, this particular issue is tracking an error in something we're already generating. Until the better samples are ready, maybe we should ameliorate this by inserting comments about fields that the user needs to populate.

**Comment by geigerj** [comment]
Tracking upstream as https://github.com/googleapis/toolkit/issues/1809.

> maybe we should ameliorate this by inserting comments about fields that the user needs to populate.

This could be very helpful. We already do have information from configuration on which fields are required, so it should be quite simple to generate a comment in the method sample whenever one of these fields does not have initialization fields specified. Filed https://github.com/googleapis/toolkit/issues/1810
