### ISSUE TITLE
Stackdriver Debugger Logpoints: Frequent 'MutationError's

### ISSUE THREAD

**Issue by premist** [GoogleCloudPlatform/google-cloud-ruby#1875]
I'm trying out Stackdriver Debugger (although it's in beta currently) and encountering Google::Cloud::Debugger::MutationError a lot. I installed Stackdriver Debugger on a Rails app, and tried to use Logpoints with multiple types of objects. 

I tried logging `params = {params}` or tried to log specific parameter like `object_id = {params[:id]}` but they all result in this logpoint message:

```ruby
LOGPOINT: params = #<Google::Cloud::Debugger::MutationError: Mutation detected!>
```

I also tried to log ActiveRecord collection in various ways like using `.to_s` or `.inspect`, but they all failed with the same error.

The only case I can use logpoint without MutationError is simple comparison(`@ar_collection.size > 4`), and it feels quite limiting. Is this intended design of the Stackdriver Debugger, and is there a way to go around it? (e.g. creating a logpoint in a certain way)

![image](https://user-images.githubusercontent.com/291078/33870867-4bc3f53e-df53-11e7-8b7a-8670f35b23e0.png)

**Comment by quartzmo** [comment]
@premist Thank you for opening this issue. I don't yet have any experience using logpoints with Rails (@thagomizer and @dazuma may be able to offer more insight), but I did notice something of interest while reading the google-cloud-debugger source code:

[Logpoint#evaluate_log_message](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-debugger/lib/google/cloud/debugger/logpoint.rb#L61) delegates to `Evaluator.readonly_eval_expression`, which in turn calls [Evaluator. readonly_eval_expression_exec](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-debugger/lib/google/cloud/debugger/breakpoint/evaluator.rb#L825-L834). When this method attempts to evaluate your expression in the given context binding, it appears to treat ALL StandardErrors as MutationError:

```ruby
                rescue => e
                  # Treat all StandardError as mutation and set @mutation_cause
                  unless e.instance_variable_get :@mutation_cause
                    e.instance_variable_set(
                      :@mutation_cause,
                      Google::Cloud::Debugger::EvaluationError::UNKNOWN_CAUSE)
                  end
``` 
Can you inspect `mutation_cause` and determine the underlying error? I suspect your expressions are failing due to the limitations of the given context and that you will need to avoid calls that depend on Rails, but that's just a guess.

**Comment by quartzmo** [comment]
@premist Any progress on this issue?

**Comment by dazuma** [comment]
@quartzmo @premist This is probably my issue. We have a mutation detector that we know is conservative and probably prevents a variety of legitimate use cases. We have a project on the books to provide a way to disable it selectively and/or whitelist additional cases. Let me take this issue.

**Comment by premist** [comment]
Sorry @quartzmo, I was quite busy on the past weeks due to some company internal milestone. I will wait until resolution comes from @dazuma and will test with the new version.

**Comment by blowmage** [comment]
@dazuma Can you give us an update?

**Comment by dazuma** [comment]
I need to complete the documentation of this item and release an update of the debugger gem. I'll be focusing on my assigned issues in the repo this week, and will take care of this.

**Comment by dazuma** [comment]
google-cloud-debugger 0.31 includes the improvements here.
