### ISSUE TITLE
Can't specify insertId for BigQuery to do de-duplication

### ISSUE THREAD

**Issue by Jiyu-Zhang-Zendesk** [GoogleCloudPlatform/google-cloud-ruby#1991]
According to BigQuery's document the user can specify `insertId` for each row. And if the same insertId is inserted twice . BigQuery can de-duplicate the data:
https://cloud.google.com/bigquery/streaming-data-into-bigquery

But actually the user can't. And `insertId` is actually "hardcoded" to some uuid here:
https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-bigquery/lib/google/cloud/bigquery/service.rb#L213

This needs to be fixed.

**Comment by quartzmo** [comment]
Hi @Jiyu-Zhang-Zendesk, thank you for opening this issue.

Currently, this library [automatically and repeatedly retries](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-bigquery/lib/google/cloud/bigquery.rb#L464-L485) failed idempotent operations such as `tabledata.insertAll`. Ensuring that the retry works correctly was [a priority of the BQ team](https://github.com/GoogleCloudPlatform/google-cloud-ruby/pull/1758#pullrequestreview-67726485) when we last worked on this method:

> generate a unique ID per row and remember those when doing retries

Are you experiencing a problem or situation in which this automatic retry facility is not meeting your needs?

/cc @jjolma

**Comment by ronan-mch** [comment]
Hi @quartzmo , Jiyu has opened the issue because we would like to take advantage of the best effort deduplication that the `insertId` enables. To do this, we set the `insertId` to a value that is unique for the event that triggers the insertion. However as far as we can see from the code that Jiyu linked to, the `insertId` is populated by the BigQuery gem itself and thus the value that we enter into the `insertId` field will be overwritten, meaning that the de-duplication value of the `insertId` field is lost. Are we understanding the code correctly? If so, how are we to take advantage of BigQuery's built-in deduplication?

**Comment by quartzmo** [comment]
I think this depends on the cause of your duplication problem. If the duplication problem is due to requests failing, and the solution is to retry the requests with backoff, then this situation is handled for you by the library. If the cause is something other than the requests failing, then maybe a change is needed. Hopefully we can get some input from the BQ team because they have (obviously) very deep experience with these issues.

**Comment by Jiyu-Zhang-Zendesk** [comment]
Hi @quartzmo, good to know that we have retry logic in the library. But our problem is a bit different here. We are handling streaming data and it's possible for the same message to be processed twice. That's why we need to leverage BQ's de-duplication mechanism, which is to set the `insertId`. Is that possible for the user to set `insertId` instead of setting by the library?

**Comment by quartzmo** [comment]
@Jiyu-Zhang-Zendesk I just noticed something in the official docs that suggests your use case may not be supported:

> If you try to stream **the same set of rows** within that time period and the insertId property is set, BigQuery uses the insertId property to de-duplicate your data on a best effort basis.

I believe in your use case, although it's possible for the same row to be processed twice, the **set** of rows in the request will always be different, is that correct?

**Comment by Jiyu-Zhang-Zendesk** [comment]
@quartzmo Regarding your questions:
(1) Will all of your duplicates fall within the 1-minute limit?
Not 100% of them. But even de-deduplication within 1-minute can help us a lot.
(2) What type of unique value do you intend to use for insertId? &
(3) What is the scope of the value's uniqueness?
We have something called `event_id` which is globally unique. We can use that for `insertId` if `insertId` works
For our use case, it's actually the same set of rows when duplication happens. We are consuming Kafka messages, and since we don't commit on each message (and we shouldn't), it is possible for the exact same row to be processed twice

**Comment by quartzmo** [comment]
@jjolma Any thoughts on this use case?

**Comment by jcondit** [comment]
Just to recap: The BQ Ruby client automatically generates an insertId internally, and uses that ID for any internal retries that it issues. However, there's a feature request for allowing the client code to specify a custom insertId so that they can do higher-level deduplication--in other words, the client code wants to deduplicate across several client-level calls to insertAll, rather than just deduplicating across internal retry attempts.

That seems like a totally reasonable feature request. If the client code specifies an insertId, use that one. If they don't, then generate a random one internally.

**Comment by quartzmo** [comment]
@jcondit Your recap sounds correct to me. Thanks for responding!

**Comment by blowmage** [comment]
@jcondit Does exposing `insertId` to users change how the client code needs to handle `InsertAll` calls? Part of the change to treat `InsertAll` as idempotent was having a reliable `insertId` value. If users are able to specify an `insertId` value (possibly with something less reliable) does that affect the client treating `InsertAll` as idempotent?

**Comment by jcondit** [comment]
IMO if the client code decides to provide an insertId, then they are taking responsibility for the deduplication semantics, and all the library needs to do is pass the insertId through using the existing API invocation and retry logic. The only risk to the client code is that they could get more deduplication than they intend if they pass the reuse an insertId for unrelated rows--but that's on them to manage.

It is still fine for the library to retry internally using the client-supplied insertId, since the only thing that matters for idempotence is that retries use the same insertId, however that happens to be generated.

**Comment by blowmage** [comment]
Sounds good. Thanks for the clarification.

**Comment by quartzmo** [comment]
@jcondit Is it true that the scope of `insertId` uniqueness is the entire project, rather than the table? Is the uniqueness scope of `insertId` documented anywhere?

**Comment by quartzmo** [comment]
I'm starting work on a PR for this feature.

**Comment by ronan-mch** [comment]
Sounds good, looking forward to seeing it.

**Comment by jcondit** [comment]
@quartzmo Scope of insertId uniqueness should be only the table, not the project.

**Comment by quartzmo** [comment]
Status update: I have switched to working on a new feature for BigQuery, but I still hope to find time to finish this work before the next release of google-cloud-bigquery. Thanks for your patience.

**Comment by julid29** [comment]
Hi All!!
Just wanted to know, has this feature been added for Java? I'm working with Kotlin and i having a rough time trying to insert TableRows into BigQuery with my custom UUID/insertId.

At first i though it would be easy since in a series of [post](https://cloud.google.com/blog/products/gcp/after-lambda-exactly-once-processing-in-cloud-dataflow-part-3-sources-and-sinks) that seems posible. Do you know of any PR for this?

Thanks!!
