### ISSUE TITLE
Couldn't get the topic belonging to other project in Pubsub API via Ruby

### ISSUE THREAD

**Issue by xinyunh0929** [GoogleCloudPlatform/google-cloud-ruby#1993]
Our customer want to publish pubsub message to the pubsub under our project.

However, they received permission alert when they try getting the topic since it isn't under their project.

Sample code; 
require "google/cloud/pubsub"

pubsub = Google::Cloud::Pubsub.new( 
project_id: "xinyunh-jobs-api", 
credentials: "/usr/local/google/home/xinyunh/key/key.json", 
scopes: ["https://www.googleapis.com/auth/pubsub"] 
)

//Get permission issue on this step. 
// The error message they're getting is: "Google::Cloud::PermissionDeniedError: 7:User not authorized to perform this action. 
from /Users/samson/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/google-cloud-pubsub-0.27.0/lib/google/cloud/pubsub/service.rb:458:in `rescue in execute'" topic = pubsub.topic "projects/aaa/topics/events"

However, we got an answer that we could make it via adding 'skip_lookup': 
topic = pubsub.topic "projects/aaa/topics/events", skip_lookup: true
msg = topic.publish "xinyunh"

Thus, we want to know is that a temporary fix or a permanent solution?

**Comment by blowmage** [comment]
> Thus, we want to know is that a temporary fix or a permanent solution?

We don't have any plans to change the API for [`#topic`](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-pubsub/v0.30.0/google/cloud/pubsub/project?method=topic-instance), which currently supports both the `project` and the `skip_lookup` arguments. Their use of the Ruby library is valid and supported.

The permission denied error is most likely because of the call to [`GetTopic`](https://cloud.google.com/pubsub/docs/reference/rpc/google.pubsub.v1#google.pubsub.v1.Publisher.GetTopic) and their account does not have permissions to that API endpoint. This API call is not made when the argument `skip_lookup` is set to `true`.

**Comment by quartzmo** [comment]
Yes, as @blowmage commented above, the following is correct and can be considered a "permanent solution":

```ruby
topic = pubsub.topic "projects/aaa/topics/events", skip_lookup: true
msg = topic.publish "xinyunh"
```

Does this answer your question? Can we close this issue?

**Comment by xinyunh0929** [comment]
Yes, thanks for the answer.
