### ISSUE TITLE
Stream file from third party provider to Google Cloud Storage?

### ISSUE THREAD

**Issue by 210rain** [GoogleCloudPlatform/google-cloud-ruby#1997]
I'm looking for a way to initiate a download of a file and upload said file without ever writing the file to disk or having the entire file in memory as some of the files we will be transferring may be large. I was trying to use IO.pipe to pass a reader to the upload_file method in Google::Cloud::Storage but it seems to want a file it can rewind which obviously you can't do with a stream. Is there a method for accomplishing this with the Google Cloud SDK?

**Comment by quartzmo** [comment]
Hi @210rain, thanks for reporting this issue.

Do you have an error backtrace, and if possible, a short script for reproducing? Thanks!

**Comment by quartzmo** [comment]
@210rain Can you provide some error details for this issue? Thank you!

**Comment by 210rain** [comment]
Sorry for the delay, here's an example of what i'm trying to do:
```
require 'google/cloud/storage'
require 'rest-client'

bucket = 'testing-object-mover'

storage = Google::Cloud::Storage.new(
  project_id: "<your-project>",
  credentials: "<your-creds>"
)

reader, writer = IO.pipe

fork do
  reader.close
  writer.write RestClient.get 'https://notepad-plus-plus.org/repository/7.x/7.5.5/npp.7.5.5.bin.x64.zip'
end
writer.close

storage.bucket(bucket).upload_file(reader, "file.txt")
```

And stack trace:
```
/home/rain/.rvm/gems/ruby-2.4.2/gems/google-cloud-storage-1.9.0/lib/google/cloud/storage/service.rb:541:in `rescue in execute': undefined method `size' for #<IO:fd 8> (Google::Cloud::Error)
	from /home/rain/.rvm/gems/ruby-2.4.2/gems/google-cloud-storage-1.9.0/lib/google/cloud/storage/service.rb:539:in `execute'
	from /home/rain/.rvm/gems/ruby-2.4.2/gems/google-cloud-storage-1.9.0/lib/google/cloud/storage/service.rb:285:in `insert_file'
	from /home/rain/.rvm/gems/ruby-2.4.2/gems/google-cloud-storage-1.9.0/lib/google/cloud/storage/bucket.rb:703:in `create_file'
	from example.rb:19:in `<main>'
example.rb:15:in `write': Broken pipe (Errno::EPIPE)
	from example.rb:15:in `block in <main>'
	from example.rb:13:in `fork'
	from example.rb:13:in `<main>'
```

**Comment by blowmage** [comment]
@210rain I think that the code you posted isn't doing what you think. `RestClient.get` will always return a `String` of the request. Its actually a subclass of a String, but the point is that the entire response is loaded into memory.

There are a couple ways to get your code working without using IO streams:

The first is to put the response into a `StringIO` object:

```ruby
require 'google/cloud/storage'
require 'rest-client'
require 'stringio'

bucket = 'testing-object-mover'

storage = Google::Cloud::Storage.new(
  project_id: "<your-project>",
  credentials: "<your-creds>"
)

file_contents = RestClient.get 'https://notepad-plus-plus.org/repository/7.x/7.5.5/npp.7.5.5.bin.x64.zip'
file_io = StringIO.new file_contents

storage.bucket(bucket).upload_file(file_io, "file.txt")
```

The second is to use open-uri which returns an "IO-like object" and doesn't write to disk AFAIK.

```ruby
require 'google/cloud/storage'
require 'open-uri'

bucket = 'testing-object-mover'

storage = Google::Cloud::Storage.new(
  project_id: "<your-project>",
  credentials: "<your-creds>"
)

file_io = open 'https://notepad-plus-plus.org/repository/7.x/7.5.5/npp.7.5.5.bin.x64.zip'

storage.bucket(bucket).upload_file(file_io, "file.txt")
```

**Comment by blowmage** [comment]
@210rain I've looked into this a bit. There doesn't appear to be any code in `google-cloud-storage` that would preclude use of an IO stream (the special case IO object returned by `IO.pipe`). The problem looks to lie in `google-api-client`, which is used to make the actual API call. There may also be issues using IO streams in `httpclient`, but I haven't been able to make the changes to get that far yet.

As my previous comment showed, there are ways to accomplish uploading data without first writing to the local file system. But all those examples load the entire file contents into memory. While I have not been able to get an upload to work with an IO stream, I think it may be possible with changes to external libraries.

Downloads by default also do not work using an IO stream. But downloads may work if gzip decompression and file content verification are disabled.

Does this answer your question to your satisfaction? Or would you like us to investigate further?

**Comment by 210rain** [comment]
That answers my question, thanks!

**Comment by artm** [comment]
I would like this to be reopened, or re-reported to the correct place.

My use case is piping a long output from a process on the remote host into a storage object.
The data won't comfortably fit into the memory of the instance where the ruby code is running and I would like to avoid writing it to a temporary file either (there are no guarantees about available space on the local file system). The relevant portion of the code:

```ruby
        rd, wr = IO.pipe
        fork do
          Net::SSH.start "xxxx", "xxx" do |ssh|
            ch.exec "xxxx" do |ch, success|
              ch.on_data do |c, data|
                wr.write data
              end
            end
          end
          wr.close
        end
        storage = Google::Cloud::Storage.new
        bucket = storage.bucket("xxxx")
        file = bucket.create_file(rd, "xxxx")
        rd.close
        Process.wait
```

the error I'm getting trying to run this is **undefined method `size' for #<IO:fd 18>**, but I due to exception re-raising in this library I fail to find where it is originally raised (indeed in an external library, but where do I find it?). 

But as far as I can guess the problem is that the API library calls `.size` on the `IO` object, but it [doesn't have such method](https://ruby-doc.org/core-2.3.1/IO.html), it's a method of its subclass [File](http://ruby-doc.org/core-2.2.0/File.html).

**Comment by blowmage** [comment]
Hey @artm, thanks for your comment.

> but I due to exception re-raising in this library I fail to find where it is originally raised (indeed in an external library, but where do I find it?).

Ruby allows your to step through from error to error using [`Error#cause`](https://ruby-doc.org/core-2.5.0/Exception.html#method-i-cause). Using this you will see that the error is caused by the `google-api-client` gem calling `#size` on the IO object to set an HTTP header for the upload. It also calls `#rewind`, which will raise when called on an IO stream object.

As I stated earlier, I have not been able to get an upload to work with an IO stream, but I think it _may_ be possible with changes to external libraries. Changes would need to be made to the [`google-api-client` gem](https://github.com/google/google-api-ruby-client), and possibly other dependencies.

**Comment by artm** [comment]
Thanks for the gem link, now I can investigate further. 

There must be a way to avoid calling `#size` and `#rewind` becase [some tools support streaming into storage](https://cloud.google.com/storage/docs/streaming).

But [apparently not in ruby](https://github.com/google/google-api-ruby-client/issues/413) as of 2 years ago.

**Comment by quartzmo** [comment]
@artm Have you discovered anything that will allow us to resolve this issue? We are not able to address it directly in this library as far as I know.

**Comment by artm** [comment]
I agree that the solution is outside the scope of your library. `google-api-ruby-client` itself [uses a third party library][1] to implement a HTTP functionality ([httpclient][2]) and limited by their choice in what they can provide. 

I would just clarify in the documentation where it suggests that the upload API accepts an `IO` instance, that it only can handle `IO` objects that implement `.size`, e.g. `File` and `StringIO`, at the moment. 

[1]: https://github.com/google/google-api-ruby-client/blob/master/google-api-client.gemspec#L28
[2]: https://github.com/nahi/httpclient

**Comment by Fonsan** [comment]
@quartzmo @artm @210rain https://github.com/googleapis/google-cloud-ruby/issues/2684
