### ISSUE TITLE
Firestore Nested Field Paths

### ISSUE THREAD

**Issue by ryanmats** [GoogleCloudPlatform/google-cloud-ruby#2050]
Hi!
I am trying to update a nested field in Firestore like in the API reference (http://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.52.0/google/cloud/firestore/documentreference?method=update-instance) but am not getting the right result.

Here is [the code I'm running](https://gist.github.com/ryanmats/3f3bb5b3672126871ca5c3f59650135e).

When I look in the Firebase console, the age does get updated from 12 to 13, but instead of updating favorites.color from Blue to Red, it adds a new field to the document called nested_field_path.

Thanks!

**Comment by blowmage** [comment]
I think this is a problem with the code example in the documentation.

This code:

```ruby
frank_ref.update({ age: 13, nested_field_path: "Red" })
```

Is the same as this:

```ruby
frank_ref.update({ :age => 13, :nested_field_path => "Red" })
```

But you don't want to use the `:nested_field_path` _symbol_, you want to use the `nested_field_path` _object_ you created the line previous. So the correct code should be:

```ruby
frank_ref.update({ age: 13, nested_field_path => "Red" })
```

I'll fix all the code examples to demonstrate using the object instead of creating a new symbol.

**Comment by blowmage** [comment]
Optionally, you can pass in a dotted field path instead of creating/using a FieldPath object:

```ruby
frank_ref.update({ age: 13, "favorites.color": "Red" })
```
