### ISSUE TITLE
Google::Cloud::InvalidArgumentError: Bad image data.

### ISSUE THREAD

**Issue by murjax** [GoogleCloudPlatform/google-cloud-ruby#2073]
I'm using `Google::Cloud::Vision` to perform a safe search operation on an image with an external url. I followed the docs for setup:
```
vision = Google::Cloud::Vision.new(project: project_id)
image = vision.image(url)
```

When I call `image.safe_search`, it throws `Google::Cloud::InvalidArgumentError: Bad image data.`. This is intermittent on some images I give it. [This is the one of the problem urls](https://s3.amazonaws.com/abnlive/photos/original/ea9bdc5fb0993016cc4402219ccc7d2db934dd11.?1524686585). What is different about this photo that is causing it to throw an exception?

**Comment by blowmage** [comment]
Hi @murjax, thanks for the issue. It looks to me like you have a corrupted image file. When I view the image I see a large gray section at the bottom of the image. My assumption here is that that you are getting an invalid argument error because the image data is bad.

![bad-image](https://user-images.githubusercontent.com/730/39639938-c6e0d9c8-4f86-11e8-8e6b-d0237bb41bf7.png)

I have been able to annotate other images using S3 URLs, but not the image URL you provided.

**Comment by quartzmo** [comment]
@murjax Does this also seem to you like a problem isolated to this single image? If so, can you close this issue?

**Comment by quartzmo** [comment]
Sorry, I meant: isolated to images with bad data.

**Comment by murjax** [comment]
Yes, this was the issue. Thanks!
