### ISSUE TITLE
Firestore - Passing Information out of Transaction Functions

### ISSUE THREAD

**Issue by ryanmats** [GoogleCloudPlatform/google-cloud-ruby#2103]
In the [Firestore documentation](https://cloud.google.com/firestore/docs/manage-data/transactions#passing_information_out_of_transactions) we have code samples in the other languages for how to pass information out of Firestore Transactions back to the caller. (I/e a simple true/false boolean for whether population is updated).

Is it possible to do this using the Ruby client? If so, how would this work?

Thanks!

**Comment by blowmage** [comment]
Hi @ryanmats, thank you for the question and for using the Ruby Firestore client.

It is possible to pass information back from a transaction, but to do this you should create a separate method context to pass values out. The Firestore transaction uses a Ruby closure which shares the [Binding](https://ruby-doc.org/core-2.5.0/Binding.html) that the closure is created in. But the transaction closure may be executed more than once in response to errors on the server. So you should wait until the transaction is complete before using the value.

Here is my take on the Python version of the documentation you referenced:

```ruby
require "google/cloud/firestore"

firestore = Google::Cloud::Firestore.new

# Get a document reference
city_ref = firestore.doc "cities/SF"

# define method that will create a transaction
def update_in_transaction firestore, city_ref
  updated = nil
  
  firestore.transaction do |tx|
    snapshot = tx.get_all(city_ref).first
    new_population = snapshot.get(:population) + 1

    if new_population < 1000000
      tx.update city_ref, population: new_population
      updated = true
    else
      updated = false
    end
  end
  
  updated
end

# call method that will create a transaction
result = update_in_transaction firestore, city_ref
if result
  puts "Population updated"
else
  puts "Sorry! Population is too big."
end
```

The Python code gets a DocumentSnapshot object from a DocumentReference object using a Transaction with this code: `snapshot = city_ref.get(transaction=transaction)`. We don't have that in Ruby yet, which is why the line `snapshot = tx.get_all(city_ref).first` is used. I would prefer that this line be this instead: `snapshot = city_ref.get transaction: tx`, so I'll create an issue to implement that.

**Comment by blowmage** [comment]
@beccca @frankyn Any idea why the Ruby example is not present on this documentation?

**Comment by frankyn** [comment]
Hi @blowmage, by this documentation you mean the [Firestore Transactions documentation](https://cloud.google.com/firestore/docs/manage-data/transactions#passing_information_out_of_transactions). @ryanmats is writing samples for Ruby.

**Comment by blowmage** [comment]
Ah, gotcha. I see what's going on now. :)

**Comment by blowmage** [comment]
BTW, my previous recollection was off. The original trade-off was to allow `Transaction#get` to get either a DocumentSnapshot or fulfill a Query. So instead of stating `snapshot = tx.get_all(city_ref).first` you can just say `snapshot = tx.get city_ref`.

**Comment by ryanmats** [comment]
@blowmage I think I'm good - thanks for all the help!
