### ISSUE TITLE
Tasks: Unable to create new client

### ISSUE THREAD

**Issue by TheRoyalTnetennba** [GoogleCloudPlatform/google-cloud-ruby#2171]
Following the instructions [here](https://github.com/GoogleCloudPlatform/google-cloud-ruby#cloud-tasks-api-alpha), creating a new client with `Google::Cloud::Tasks::V2beta2.new` fails with `ArgumentError: unknown keyword: interceptors" from google-gax-1.2.0/lib/google/gax/grpc.rb:110`.

**Comment by TheRoyalTnetennba** [comment]
Works when using google-gax-1.3.0.

**Comment by blowmage** [comment]
Updating the `google-gax` dependency to `~> 1.3` should fix this then. I would release this change as release `0.2.1`, and yank release `0.2.0`.

**Comment by blowmage** [comment]
The `interceptors` keyword argument is used by the updated GAPIC code in the following gems:

* `google-cloud-speech`
* `google-cloud-text_to_speech`
* `google-cloud-video_intelligence`
* `google-cloud-vision`

Not all of these gems have had releases since the GAPIC code was updated, but all gems should have the same fix applied, not just `google-cloud-tasks`.

**Comment by dazuma** [comment]
Good catch @blowmage. So (1) we need to update those gemspecs, (2) the generated gemspec needs to be updated in gapic-generator, and (3) we need to figure out how to cause synthtool to update an existing gemspec the next time a regeneration requires a newer gax version.

@TheRoyalTnetennba can you update https://github.com/GoogleCloudPlatform/google-cloud-ruby/pull/2172 to include the other gems?

I'll open a gapic-generator issue for (2), and open a new issue here for (3) because it's our synth scripts.

**Comment by quartzmo** [comment]
@dazuma Would it also be possible to update the generator to add a test to each package covering this error?

**Comment by dazuma** [comment]
@quartzmo Possibly yeah. In general, tests for problems with how regeneration is merging the newly generated code with the existing code. I'll think about that. It probably falls more on my and Graham's (and Thea's) plate than on gapic itself.

**Comment by TheRoyalTnetennba** [comment]
@dazuma @blowmage I merged. I'll make a new branch with the other gemspec fixes.

**Comment by blowmage** [comment]
It is possible the tests already cover the use of the `interceptors` named argument, since they are present. But CI is always building with the latest dependencies so we may have never saw it.

If CI was less painful it might be nice to run tests with the most up to date dependencies, and the most out of date.

**Comment by TheRoyalTnetennba** [comment]
Getting failures on the speech stream tests with and without changing gemspec. Does anyone have extra context on that?

**Comment by blowmage** [comment]
What is the error? Have you enabled the API?
