### ISSUE TITLE
Lookup seems to be limited to 300 records

### ISSUE THREAD

**Issue by dmush** [GoogleCloudPlatform/google-cloud-ruby#2275]
A have a single entity in datastore. I try to lookup (find_all) 426 keys at once. Among these 426 keys I have the key of existing entity. If the key is among first 300 items in array then the lookup result contains the entity. Otherwise lookup result doesn't contain it.

Is this a bug? Or am I doing something wrong?

**Comment by blowmage** [comment]
Hi @dmush, thanks for the question. You are doing nothing wrong, this is how the Datastore API works. Results have a max limit of the number of entities that can be returned, and a max limit for the amount of data that can be returned. If your entities were all ~1MB each, you would only get 4 in the response.

However, we have added the [`QueryResult#all`](http://googlecloudplatform.github.io/google-cloud-ruby/docs/google-cloud-datastore/latest/Google/Cloud/Datastore/Dataset/QueryResults.html#all-instance_method) helper method to make iterating across these results much easier.

```ruby
require "google/cloud/datastore"

datastore = Google::Cloud::Datastore.new

query = datastore.query "Task"
tasks = datastore.run query
tasks.all do |t|
  puts "Task #{t.key.id} (#cursor)"
end
```

You can even specify the maximum number of API requests that should be made:

```ruby
require "google/cloud/datastore"

datastore = Google::Cloud::Datastore.new

query = datastore.query "Task"
tasks = datastore.run query
tasks.all(request_limit: 10) do |t|
  puts "Task #{t.key.id} (#cursor)"
end
```

Does this answer your question?

**Comment by dmush** [comment]
Hi @blowmage, thanks for your answer. The thing here is that I didn't change anything except the keys order in an array that is argument to find_all. And the response is a single entity with two boolean fields. I don't think it reaches the data limit.

For example I have a single entity in Datastore with data of a size that below the limit. In this case if I generate 299 fake keys and add a valid key to that entity (300 keys in all) then I get an array with a single item in it. And this item is my entity. But if I generate 300 fake keys (301 keys with the valid key in the end of this array) then I get an empty lookup response. And if I use the same 301 keys but reversed (or just valid key somewhere in the middle of that array) then I get my entity in the lookup response.

**Comment by blowmage** [comment]
I didn't real your question very well. Since you are using `find_all` you want to use [`LookupResults#all`](http://googlecloudplatform.github.io/google-cloud-ruby/docs/google-cloud-datastore/latest/Google/Cloud/Datastore/Dataset/LookupResults.html#all-instance_method) instead of `QueryResult#all`. Apologies for my mixup.

```ruby
require "google/cloud/datastore"

datastore = Google::Cloud::Datastore.new

task_key1 = datastore.key "Task", "sampleTask1"
task_key2 = datastore.key "Task", "sampleTask2"
tasks = datastore.find_all task_key1, task_key2
tasks.all do |t|
  puts "Task #{t.key.id} (#cursor)"
end
```

300 is a very common limit for Datastore. I've occasionally seen more results returned, but that is for very small sets just slightly larger than 300. If the set size grows much larger then the API response drops to 300 results and forces you to make additional API calls. I suspect this is due to some internal limits. Again, you are doing nothing wrong, this is how the API is documented to work. There are no guarantees on how many results will be returned in any since API response.

> But if I generate 300 fake keys (301 keys with the valid key in the end of this array) then I get an empty lookup response.

It may be empty, but what does `LookupResults#next?` return? There is likely another page of results the API is indicating can be returned.

**Comment by dmush** [comment]
It works, thanks. Sorry, that was my mistake. I missed the `.all`. Now it works expected.
