### ISSUE TITLE
Blank page in Documentation

### ISSUE THREAD

**Issue by KeweiCodes** [GoogleCloudPlatform/google-cloud-ruby#2282]
http://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-vision/v0.30.0/google/cloud/vision/project?method=annotate-instance

leads to the below:

<img width="1275" alt="screen shot 2018-08-14 at 11 44 40 am" src="https://user-images.githubusercontent.com/10202555/44064090-7a80498e-9fb7-11e8-806d-efb12c5a885b.png">

**Comment by quartzmo** [comment]
@KeweiCodes Thank you for reporting this issue!

I believe this is caused by the formatting of the documentation for the `requests` param in [Project#async_batch_annotate_files](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-vision/lib/google/cloud/vision/project.rb#L287-L288). Because the type information is placed on the next line, it winds up in the description rather than in the `types` attribute:

```
"params": [
        {
          "name": "requests",
          "types": null,
          "description": "[Array&lt;Google::Cloud::Vision::V1::AsyncAnnotateFileRequest | Hash&gt;]\nIndividual async file annotation requests for this batch.\nA hash of the same form as\n  <code>Google::Cloud::Vision::V1::AsyncAnnotateFileRequest</code> can also be\nprovided.",
          "optional": false,
          "nullable": false
        },
```

A fix would be to move the type information to the line above, then disable the rubocop warning for this method.

**Comment by blowmage** [comment]
@quartzmo Can you manually fix the JSON files so the URL provided in this issue works?
