### ISSUE TITLE
Google Drive and Google Cloud Print

### ISSUE THREAD

**Issue by JohnSmall** [GoogleCloudPlatform/google-cloud-ruby#2343]
It's nice to have all this stuff, but what about the basics? I can't find the api for Google Drive or Google Cloud Print are they not here?

**Comment by blowmage** [comment]
Hi @JohnSmall, thanks for the question. This repo is contains the ruby libraries for clients of the [Google Cloud Platform APIs](https://cloud.google.com). Unfortunately, Google Drive and Google Cloud Print are not GCP APIs and because of that their gems would not be hosted in the git repo.

[Google Drive](https://developers.google.com/drive/api/v3/about-sdk) has an API and clients. You can find out more about them here:

https://developers.google.com/drive/api/v3/downloads

The gem you are looking for is [google-api-client](https://rubygems.org/gems/google-api-client), and the repo is [google/google-api-ruby-client](https://github.com/google/google-api-ruby-client). This gem has clients for both `drive_v3` and `drive_v2` APIs. You can see more by checking out the [Ruby Quickstart](https://developers.google.com/drive/api/v3/quickstart/ruby) for Drive. Or view the documentation for [DriveV3](https://www.rubydoc.info/gems/google-api-client/Google/Apis/DriveV3) and [DriveV2](https://www.rubydoc.info/gems/google-api-client/Google/Apis/DriveV2).

Unfortunately, I wasn't able to find out much about [Cloud Print](https://developers.google.com/cloud-print/). The [API is described here](https://developers.google.com/cloud-print/docs/appInterfaces), but it doesn't appear to be discoverable by Google's [Discovery API](https://developers.google.com/discovery/), and because of that the API is not part of the google-api-client gem. I asked a couple of folks who work at Google about this but they were not aware of any supported clients for the API. 

Does this help? Do you have any other questions?

**Comment by JohnSmall** [comment]
Thanks for the quick reply. I'm new to the Google API ecosystem and finding it hard to find my way around. I'll check out the links you've included and see if I can work something out myself. 

Is there a reason why Google Drive isn't part of the Google Cloud Platform APIs ? To me it suggests there's some sort of dividing line inside the Google suite so that some things you'd expect to be included aren't, e.g. Drive and Print, are there others? Where can I find out about the dividing line?

I did find a very old (2011) Python example of using the Cloud Print API, [https://developers.google.com/cloud-print/docs/pythonCode](https://developers.google.com/cloud-print/docs/pythonCode). It comes with a warning that it's out of date. But the Cloud Print is listed as a beta, which suggests it's been in beta since 2011, and is therefore not a priority. 

I need to use it because I have an EC2 hosted web site that has to print order sheets on an office printer as orders come in from customers. It's quite a tricky integration.

**Comment by blowmage** [comment]
> Is there a reason why Google Drive isn't part of the Google Cloud Platform APIs ?

They are two separate products. Google Cloud Platform has a Storage API, similar to AWS's S3.

https://cloud.google.com/storage/

**Comment by blowmage** [comment]
I did find a couple open source gems for integrating with Cloud Print. I don't know anything about them other than they exist, however.

https://github.com/thegengen/cloudprint
https://github.com/dsaronin/kinokero

Good luck!
