### ISSUE TITLE
Pub/Sub:   Infinite Loop on `sleep for a 1001 milliseconds` in Rails app. 

### ISSUE THREAD

**Issue by wintheday** [GoogleCloudPlatform/google-cloud-ruby#2354]
Environment:

```yml
Rails: 4.2.10
Ruby: 2.3.5
google-cloud-pubsub: 0.32.0
MacOS: 10.12.6 Sierra
```

In the rails console I run:

```ruby
project = Google::Cloud::Pubsub.new(
    project_id: 'my-project-id', 
    credentails: 'path-to-cred-file'
)
```
```ruby
project.topics
```

When this runs with default settings the request just hangs.

I know that the config for Pubsub above is correct as I have used the same thing in a smaller Rails 5.2 application and it worked perfectly.

Also, when I run this against the pubsub emulator locally it works perfectly. 

It seemed as though this issue was in the GRPC layer so I enabled these ENV variables.

```
GRPC_TRACE=all
GRPC_VERBOSITY=debug
```

When I ran the same code above with those enabled, I got a lot of startup logs and then it started looping with this output with incrementing values.

```
I0823 ... timer_generic.cc:715]       TIMER CHECK BEGIN: now=8028 next=9223372036854775807 tls_min=7018 glob_min=8023
I0823 ... timer_generic.cc:610]         .. shard[0]->min_deadline = 8023
I0823 ... timer_generic.cc:533]         .. shard[0]: heap_empty=true
I0823 ... timer_generic.cc:508]         .. shard[0]->queue_deadline_cap --> 9028
I0823 ... timer_generic.cc:573]         .. shard[0] popped 0
I0823 ... timer_generic.cc:628]         .. result --> 1, shard[0]->min_deadline 8023 --> 9029, now=8028
I0823 ... timer_generic.cc:737]       TIMER CHECK END: r=1; next=9029
I0823 ... timer_manager.cc:175]       sleep for a 1001 milliseconds
I0823 ... timer_manager.cc:190]       wait ended: was_timed:1 kicked:0
```

I can post more info on my application's dependencies as well as further data from the above GRPC logging if necessary.

**Comment by blowmage** [comment]
I just tried this from a rails app and it worked fine.

```
$ bundle exec rails console
Running via Spring preloader in process 4057
Loading development environment (Rails 5.2.1)
irb(main):001:0> require "google/cloud/pubsub"
=> true
irb(main):002:0> pubsub = Google::Cloud::Pubsub.new
=> #<Google::Cloud::Pubsub::Project:0x00007fe0e4bd7050 @service=Google::Cloud::Pubsub::Service(my-project-id)>
irb(main):003:0> pubsub.topics
=> [...]
```

A few thoughts here.  Since this works for me on a Rails app, and it works for you on a "smaller Rails 5.2" app, then the problem is very likely something to do with your specific Rails app.

The GRPC library is also used when connecting to the pubsub emulator, so again, I would look for other explanations before diving too deep in to GRPC. If GRPC ran into an unexpected problem it would raise an exception. The sleep message looks to be from a thread that manages timeouts, so I wouldn't be overly concerned about it.

Debugging is difficult, and unfortunately there just isn't enough information here for us to diagnose what is going on. Here is what I would suggest:

1) Create a new rails app, add google-cloud-pubsub, and verify it works
2) Start adding each dependency from the app that is failing, one at a time, and check to see that pubsub still works (using both the emulator and live API)
3) Add any other configuration from the failing app, and check to see that pubsub still works (using both the emulator and live API)

At some point pubsub will stop working, and you will then know which dependency or configuration is causing the problem.

**Comment by wintheday** [comment]
@blowmage Thanks for the advice I will step through my dependencies and see what is causing a conflict with the Cloud Pub/Sub gem.  

Since this doesn't seem to be a direct issue in the Cloud Pub/Sub gem you can close this issue and I can post my findings on StackOverflow or I can follow up here and post what is causing the conflict whichever you would prefer.

**Comment by blowmage** [comment]
Are you seeing this in your local environment? Or your production environment?

**Comment by wintheday** [comment]
Both, this happens locally when I remove the emulator variable and in production when deployed to GKE.

**Comment by blowmage** [comment]
Are you running multiple threads locally? If so, are you creating a Pub/Sub client (or any other GRPC client) _pre-fork_?

**Comment by wintheday** [comment]
I create a single Pub/Sub client pre-fork, make some GRPC calls to ensure that the connection is valid than fork treads to start multiple listeners against PubSub subscriptions. 

If you are interested the gem/repo I created for this is public and available here: [Subserver](https://github.com/lifechurch/subserver). 

Note: The subserver gem works perfectly in the same Rails 5.2 environment mentioned before.

**Comment by blowmage** [comment]
Unfortunately you can't create a GRPC client pre-fork. This is because GRPC is currently unable to be forked. You need to delay creating any GRPC client until after the web server forks the main thread to create worker threads. See the discussion on this in #691 and #1860, and the GRPC bug grpc/grpc#7951.

The workaround we suggest is adding something like the following to your `config/application.rb` file, or an initializer, and using this mechanism to acquire the Pub/Sub client in your app. This will share one client per thread. If the thread is killed and restarted, a new client will be created.

```ruby
require "google/cloud/pubsub"

Google::Cloud::Pubsub.configure do |config|
  config.project_id = "..."
  config.credentials = "..."
end

module MyApplicationModule
  def self.pubsub
    Thread.current[:pubsub] ||= Google::Cloud::Pubsub.new
  end
end
```

**Comment by wintheday** [comment]
Ahh, I see good to know.  I will update Subserver accordingly so that all threads create their own GRPC client after they are forked.  With that said how would you advise validating the 
```
Google::Cloud::Pubsub.configure do |config|
  config.project_id = "..."
  config.credentials = "..."
end
```
In the main thread before the application forks?

Also, would this still have an impact on the originally posted hangup issue since it was occurring in the rails console in a single thread environment?

**Comment by blowmage** [comment]
If you create a GRPC client and then fork the thread, the GRPC client will hang on the forked threads. 

I don't know about the console, I'm not seeing that behavior. You will still have to debug what your app is doing to cause that. I would assume its related to your configuration and forking though.

**Comment by wintheday** [comment]
@blowmage Thanks for your help.  It turns out it was related to some older google dependencies that we are no longer using. 

specifically these 
```ruby
gem 'google-api-client', '= 0.17.0'
gem 'google-cloud-bigquery', '~> 0.30.0'
gem 'google-cloud-storage', '~> 1.9'
```

Removing those fixed the hangup issue.  Thanks for your help. 

Now, I can open another issue / question on this if needed but as you pointed out above you can't create a GRPC client prior to forking threads. So, how do you recommend testing that valid GCP credentials were given? 

For subserver I do the following
```
start CLI and import args
load configuration file

create a Pub/Sub client to test configuration <-
exit and throw error if invalid config. 

load subscribers
fork per subscriber and call listen
```
Should each thread do its own check to validate the connection?  That seems redundant.

**Comment by blowmage** [comment]
If each thread has a connection I would think each thread verifies the connection. You can do that as part of the creation process.

**Comment by wintheday** [comment]
Okay sounds good.  Thanks again for your help, and for your work on this gem.  

If you are at all interested and have the time, I would love any other feedback you may have on my implementation of Google Pubsub in [Subserver](https://github.com/lifechurch/subserver).
