### ISSUE TITLE
[Documentation Issue] 

### ISSUE THREAD

**Issue by harrisreynolds** [GoogleCloudPlatform/google-cloud-ruby#2404]
The link to "Authentication Guide" just takes you right back to this page.  Kinda useless and annoying.

**Comment by quartzmo** [comment]
This should be fixed with #2338. In the meantime, you can view the authentication guide in GitHub at:

`https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/<gem_name>/AUTHENTICATION.md`

For example: 

https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-storage/AUTHENTICATION.md

Thank you for your patience!

**Comment by blowmage** [comment]
This has been changed in #2338. Some links may not work until the gem are released.
