### ISSUE TITLE
Create file from blob

### ISSUE THREAD

**Issue by tattansp** [GoogleCloudPlatform/google-cloud-ruby#305]
Hello,

I'm trying to upload an image created in-line with rmagick (imagemagick), but when I try to upload it with: 

``` ruby
bucket.create_file  canvas , "/path/file.extension" 
```

I get this error: no implicit conversion of Magick::Image into String

and if I try:

``` ruby
bucket.create_file  canvas , "/path/file.extension" 
```

I get this error: `string contains null byte`

Of course because is expecting a String argument (the path where the file I want to upload is ), but I cannot find any documentation on how to upload an in-line image or a blob image.

Any ideas?

**Comment by blowmage** [comment]
Hi @tattansp, thanks for opening the issue. Right now gcloud only supports uploading a File object, or a string of the path to a file on the file system. It doesn't support uploading IO objects or StringIO objects. Yet. For a workaround I would suggest writing the image to a temp file and uploading that.

```ruby
require "tempfile"

Tempfile.open do |tmpfile|
  tmpfile.write canvas
  bucket.create_file tmpfile, "/path/file.extension"
end
```

Uploading an in-memory object is on the roadmap. The upcoming 0.9 release of [Google API Client](https://github.com/google/google-api-ruby-client), which gcloud uses to connect to the Google Cloud API, will support this. Until then, I'd love to know if the tempfile workaround works for you.

**Comment by tattansp** [comment]
Hi @blowmage I manage to workaround with a Tempfile


		file = Tempfile.new("#{name}.png")
		file.binmode
		file.write canvas.to_blob
		file.close
                bucket.create_file file.path,  "/path/file.png", metadata: {'Content-Type'=> 'image/png'}

but now I cannot make the metadata work. I upload the image but when I go to the image link the image is downloaded to my HD, and the content type of the file is "application/octet-stream", I tried with that code and with   metadata: {content_type: 'image/png'} but didn't work either. I also tried to specify a Cache-Control header but was the same. I don't receive any error, it just doesn't work.

I also would like to know how to make the image public when uploading.

Can you help me with that?

**Comment by blowmage** [comment]
Hey @tattansp, I would be honored to help. I hope we can. I think the problem here is that the name of the file that `Tempfile.new` returns does not use the given file extension. Unfortunately, right now gcloud determines the content-type from the file extension, and we don't have a way to override it. Yet.

This means that calling `Tempfile.new "image.png"` will return a file with a name something like `image.png20150911-81616-10hdzmu`. In order to have the tempfile maintain the file extension, we need to pass an array of two strings, like `Tempfile.new ["image", ".png"]` which will return a file name something like `image20150911-81616-r8yf0p.png`.

With this slight change I believe you can use the following code to get the uploaded file to use the correct content-type:

```ruby
file = Tempfile.new [name, ".png"]
file.binmode
file.write canvas.to_blob
file.close
bucket.create_file file.path,  "/path/file.png"
```

For the record, we are unhappy with this workaround and are working on making this better. You can follow #92 for the improvements we will be making to the storage API.

**Comment by blowmage** [comment]
Hey @tattansp, I spent some time on this and ran into issues when uploading a non-File IO object. By that I mean the file contents are provided in a StringIO object instead of a File object. The problem is that after uploading the file contents subsequent Storage API calls will fail. I suspect that somehow the upload process is being left open. Unfortunately I haven't been able to diagnose this completely, so you will have to continue with the Tempfile workaround for now.

I hope we can get this working in the future, but for now I'm going to place this issue on hold.

**Comment by shenbakeshkishore** [comment]
Hi,

Is it possible to upload StringIO or BytesIO file in google-cloud-storage now?
If yes, please share the guideline to be followed for python...

**Comment by quartzmo** [comment]
@shenbakeshkishore I'm sorry, I don't understand. Is this request for [google-cloud-python](https://github.com/GoogleCloudPlatform/google-cloud-python/issues)?
