### ISSUE TITLE
Backoff Questions

### ISSUE THREAD

**Issue by jeffmendoza** [GoogleCloudPlatform/google-cloud-ruby#723]
Will the docs link to the [backoff page](https://googlecloudplatform.github.io/gcloud-ruby/docs/master/Gcloud/Backoff.html) on the left nav?

Is Pub/Sub using backoff currently?

**Comment by quartzmo** [comment]
@jeffmendoza 

The "curated" docs do not currently list Backoff in the left nav, although we can certainly revisit this decision. The "standard Ruby" docs [list all types in the left nav](http://www.rubydoc.info/gems/gcloud). We have [an open issue](https://github.com/GoogleCloudPlatform/gcloud-ruby/issues/543) to refer readers from the curated docs to the rubydoc.info docs in order to help them locate types such as Backoff. Would love to hear your input as to whether you think that will be adequate.

Yes, all Pub/Sub gRPC requests are currently made via [this backoff method](https://github.com/GoogleCloudPlatform/gcloud-ruby/blob/v0.10.0/lib/gcloud/pubsub/service.rb#L321-L325).

**Comment by jeffmendoza** [comment]
Thanks for the quick response. Yes a link to rubydoc.info seems appropriate. 

The reason I ask is that we have this section on retry handling: https://cloud.google.com/pubsub/configure#retry-handling For the 'Ruby' tab we can mention that gcloud-ruby handles backoff and link to the backoff doc.

**Comment by quartzmo** [comment]
@jeffmendoza That sounds great!!! Looking forward to seeing gcloud-ruby docs on https://cloud.google.com/pubsub !

**Comment by blowmage** [comment]
It would be nice to have Backoff and Upload listed on the left navigation somewhere. We used to have a full API listing in the previous doc site. We should make sure we link to Backoff from all the service overview docs too.

**Comment by quartzmo** [comment]
@blowmage: I agree, #721 should definitely add top-level docs to each service that explain how to configure retries, etc.

**Comment by quartzmo** [comment]
This is related to #808.  It should be resolved by documenting GAX `client_config` in most services.

**Comment by blowmage** [comment]
Agreed. Backoff has been removed completely, so this could probably be closed.

**Comment by quartzmo** [comment]
Closed by #959.
