### ISSUE TITLE
Links in the google-cloud-logging pages are broken

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/google-cloud-ruby#913]
Navigating to the root of the [Google Cloud Logging](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-logging/v0.20.1/google/cloud/logging), you'll notice that all the links at the top are broken.

We need to fix them basically.

![image](https://cloud.githubusercontent.com/assets/6609430/18733330/c6ab90c6-801e-11e6-825e-c0bab95b5bd6.png)

**Comment by quartzmo** [comment]
These anchors are broken due to the hashbang-based routing in the single-page Angular app. 

The sub-headings have the correct `id`s: `<h2 id="listing-log-entries" class="ng-scope">Listing log entries</h2>`, but that is not the problem.

See GoogleCloudPlatform/gcloud-common#40, GoogleCloudPlatform/gcloud-common#136, and GoogleCloudPlatform/gcloud-common#137. (I wonder if we should close one or two of these issues as duplicates?)

@callmehiphop @stephenplusplus Is the best thing to do right now simply to remove these links?

**Comment by callmehiphop** [comment]
> Is the best thing to do right now simply to remove these links?

It might be a good move. This is definitely something that needs to be addressed though.. 

Instead of using `<a>` tags to deeplink, we could create a directive/data attribute that can be used to generate an `<a>` tag that creates the appropriate deeplink url? `<a data-section="listing-log-entries">Read and filter log entries</a>`.

**Comment by quartzmo** [comment]
@callmehiphop Sounds good. If you can use "anchor" in the directive name it will make it easy for me to find it in the future. Something in the spirit of the `gotoAnchor` function in the [$anchorScroll](https://docs.angularjs.org/api/ng/service/$anchorScroll) example.

**Comment by quartzmo** [comment]
I'm going to resolve this issue by removing these links (and any similar anchor convenience links in the documentation.)

**Comment by callmehiphop** [comment]
Sure, `data-anchor`? I only suggest putting it behind a data attribute for portability if we ever decide to not use Angular.

**Comment by quartzmo** [comment]
@callmehiphop Yes, sounds great. Actually, I'll hold off on removing the links to see if this works.

**Comment by callmehiphop** [comment]
Sounds good, I'll try and get something for you to test this afternoon then!

**Comment by quartzmo** [comment]
This was fixed by the PRs linked above, and has been applied to the site.
