### ISSUE TITLE
How to instantiate a client after installing google-cloud-{api}

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/google-cloud-ruby#927]
Thanks to our modularization, we can now do `gem install google-cloud-bigquery` and then simply use the BigQuery client. This can be done in the following manner today:

```
require "google/cloud/bigquery"
bigquery = Google::Cloud.bigquery "publicdata"
dataset = bigquery.dataset "samples"
```

A question that I had was to know if we also wanted to support the following way of instantiating a client:

```
require "google/cloud/bigquery"
bigquery = Google::Cloud::Bigquery.new "publicdata"
dataset = bigquery.dataset "samples"
```

Is that more idiomatic or expected basically? 

/cc @jgeewax @dazuma @jmuk @blowmage @quartzmo

**Comment by blowmage** [comment]
Determining whether one is more idiomatic than the other is subjective, but for me I'd say `bigquery = Google::Cloud::Bigquery.new` is probably a bit more idiomatic ruby than `gcloud = Google::Cloud.new; bigquery = gcloud.bigquery "publicdata"`. However, @jgeewax has expressed a strong vision of creating a top level `gcloud` object instance that all services would use to connect to. And we've tried to implement that vision as best we can.

I would consider `bigquery = Google::Cloud.bigquery "publicdata"` and `bigquery = Google::Cloud::Bigquery.new "publicdata"` to be the same operation, just with a slightly different mechanic. The only difference is that the latter would need `require "google/cloud/bigquery"`, where as the current examples only need `require "google/cloud"`. This is because those service classes are not loaded into ruby until the `gcloud` methods are called. This mechanic is in place so that only the code that users use is loaded into memory.

All in all, I'm in favor of adding `bigquery = Google::Cloud::Bigquery.new "publicdata"` as a way to instantiate the service.

**Comment by quartzmo** [comment]
I agree, I'm in favor of adding `bigquery = Google::Cloud::Bigquery.new "publicdata"` (and similar) as a way to instantiate each service.

**Comment by omaray** [comment]
Okay,  @jgeewax any objections?

Also, just to confirm, the current ways (plural) of doing the require and instantiation won't change right? Meaning we will support what we are doing today even if we add the new approach?

... because a lot of samples are doing for instance:

```
require "google/cloud"
gcloud = Google::Cloud.new "my-gcp-project-id"
pubsub = gcloud.pubsub
```

And of course we still want them to work!

**Comment by blowmage** [comment]
Yes, this proposed change would be additive. The current behavior will not change.

**Comment by quartzmo** [comment]
Although it will be additive and preserve the existing API, it is important to decide which approach to show in documentation, especially in headline examples such as those in the README. Any opinions?

**Comment by blowmage** [comment]
I'll defer to what @jgeewax and @omaray think.
