### ISSUE TITLE
Storage watch and channels?

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/google-cloud-ruby#93]
Do we support watch and channels?

https://cloud.google.com/storage/docs/json_api/v1/objects/watchAll
https://cloud.google.com/storage/docs/json_api/v1/channels/stop

These APIs are not called in the node or python projects.

**Comment by Capstan** [comment]
Is it easy to spawn/host a webhook in ruby? If so, and the developer can validate that the site is owned and [registers it as a valid push destination](https://console.developers.google.com/project/_/apiui/notification), then they could set up subscriptions. It requires [`OWNER / FULL_CONTROL`](https://cloud.google.com/storage/docs/access-control#permissions) permission on the bucket.

Especially if you yield [signed URLs](https://cloud.google.com/storage/docs/access-control#Signed-URLs) or [POST policies](https://cloud.google.com/storage/docs/reference-methods#policydocument) into generated web pages, allowing their users to upload content directly to GCS, and when it's done, take action on it.

It's somewhat of an advanced feature, since you are forced to run your own web endpoint and, since there's no associated authorization, the webhook essentially has to be an unguessable URL so other internet denizens don't find it and send you junk. But, if you're already running a web server, that's most of the battle. (Much harder for your average mobile client.)

**Comment by jgeewax** [comment]
> there's no associated authorization

There's no way at all for GCS web-hooks to prove that they indeed did come from GCS ? That's cray. Are we working on something for that?

**Comment by Capstan** [comment]
I err. You specify a client token that you validate on incoming messages: See https://cloud.google.com/storage/docs/object-change-notification#_Terminology

**Comment by danoscarmike** [comment]
Hi Mike, closing this.  Please reopen with more description if still relevant.  Thanks.  Dan
