### ISSUE TITLE
Way to create schema during the table's load

### ISSUE THREAD

**Issue by AlfonsoUceda** [GoogleCloudPlatform/google-cloud-ruby#939]
Hi:

I'd like to know if there is a way to create the schema atomically when you load the file, an example is the google-cloud-sdk with the bq binary:

`bq load ds.new_tbl ./info.csv ./info_schema.json`
or you can use the `--schema` option:
`bq load ds.new_tbl ./info.csv --schema=./info_schema.json`

I ask this because this operation is atomic and I need this behaviour with the gem, why? some of my tables are dynamic.

Cheers

**Comment by AlfonsoUceda** [comment]
I have a fork adding `schema` option to `#load` table method and I could do the following:
```ruby
csv_file = File.open("test.csv", "r")

schema = Google::Cloud::Bigquery::Schema.from_gapi(nil)
schema.string "first_name", mode: :nullable
schema.string "last_name", mode: :nullable
schema.integer "age", mode: :nullable
gapi_schema = schema.to_gapi

table.load csv_file, write: 'truncate', schema: gapi_schema
```
This works, I can modify the schema, the CSV and I can add more fields and works perfect but it isn't an elegant solution in my opinion.

Are you opened to accept a PR for adding `schema` options in `#load` table method?

**Comment by quartzmo** [comment]
@AlfonsoUceda Yes! I see no reason why not to support [`configuration.load.schema`](https://cloud.google.com/bigquery/docs/reference/v2/jobs#configuration.load). (And apologies that it slipped by us!) Please proceed with your PR and let us know if we can help in any way.

**Comment by blowmage** [comment]
One way we specify schema in `#create_table` is to specify the schema's fields:

```ruby
require "google/cloud"

gcloud = Google::Cloud.new
bigquery = gcloud.bigquery
dataset = bigquery.dataset "my_dataset"

schema_fields = [
  Google::Cloud::Bigquery::Schema::Field.new(
    "first_name", :string, mode: :required),
  Google::Cloud::Bigquery::Schema::Field.new(
    "cities_lived", :record, mode: :repeated
    fields: [
      Google::Cloud::Bigquery::Schema::Field.new(
        "place", :string, mode: :required),
      Google::Cloud::Bigquery::Schema::Field.new(
        "number_of_years", :integer, mode: :required),
      ])
]
table = dataset.create_table "my_table", fields: schema_fields
```

Can we make `Table#load` use the same API?

```ruby
schema_fields = [
  Google::Cloud::Bigquery::Schema::Field.new(
    "first_name", :string, mode: :required),
  Google::Cloud::Bigquery::Schema::Field.new(
    "cities_lived", :record, mode: :repeated
    fields: [
      Google::Cloud::Bigquery::Schema::Field.new(
        "place", :string, mode: :required),
      Google::Cloud::Bigquery::Schema::Field.new(
        "number_of_years", :integer, mode: :required),
      ])
]
table.load csv_file, write: :truncate, fields: schema_fields
```

**Comment by AlfonsoUceda** [comment]
Hi folks:

Thank ypu for your answers. I'll elaborate the PR tomorrow and we can work in it.

Thanks so much!

**Comment by blowmage** [comment]
Hey @AlfonsoUceda, I would prefer the following API:

```ruby
csv_file = File.open "test.csv", "r"

schema = bigquery.schema do |s|
  s.string "first_name", mode: :nullable
  s.string "last_name", mode: :nullable
  s.integer "age", mode: :nullable
end

table.load csv_file, write: :truncate, schema: schema
```

Would this work for you?

@quartzmo We would have to support both the `fields` array and `schema` object as parameters to `Project#create_table` and `Table#load`, and note in the documentation that one will have precedence over the other. That work for you?

**Comment by quartzmo** [comment]
@blowmage I like this design. I think `schema` should have precedence over `fields`, and that the examples should only show `schema`.

@AlfonsoUceda I think @blowmage has a nice design, do you have any concerns about it?

**Comment by AlfonsoUceda** [comment]
Folks thanks for the feedback, I'll work in that API and I'll update this PR ;)

**Comment by quartzmo** [comment]
@AlfonsoUceda great, thank you!

**Comment by blowmage** [comment]
I've looked into this in more detail, and I've decided to close this issue without implementing any changes. I want to explain why.

When we originally implemented BigQuery we were aware of the [options to define a schema](https://cloud.google.com/bigquery/docs/reference/v2/jobs#configuration.load) for a table as part of the load process. However, we decided against implementing a mechanism to configure the schema because it didn't fit in to the Ruby API we were exposing to users.

There are several options in the load configuration that we don't support, one is [configuration.query.createDisposition](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs#configuration.query.createDisposition), which controls whether the table specified should be _created_. We don't support it because the Ruby API requires a table to be created _before_ a load operation can be called on it. This decision was made in an effort to simplify the API surface area Rubyists would have to consume in order to use BigQuery.

The steps for loading data into a new table are as follows:

1. Create a table
2. Configure the table's schema
3. Load data into the table

All three of these steps can be performed by BigQuery's [jobs.insert](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/insert) API call using [configuration.load](https://cloud.google.com/bigquery/docs/reference/v2/jobs#configuration.load), but the Ruby API doesn't expose it this way. The Ruby API currently requires these steps to be made sequentially.

The Ruby API can combine the first two steps, creating a table and configuring the schema, into a single BigQuery API call. So I see no reason to add the additional complexity to the Ruby API to allow the last two steps in a single BigQuery API call. It isn't reducing the number of BigQuery API calls that need to be made.

I can see an argument for a `Dataset#load` method that will allow the creation of a table, configuring of a schema, and loading of data in a single BigQuery API call. If that is what is wanted I would respectfully ask that a new issue be opened for that.
