### ISSUE TITLE
Broken requires in gapic code for pubsub

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/google-cloud-ruby#942]
Unfortunately we didn't catch this before merging #925: 

The require statement `require "google/iam/v1/iam_policy_services_pb"` in [`publisher_api.rb`](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-pubsub/lib/google/cloud/pubsub/v1/publisher_api.rb#L171) and [`subscriber_api.rb`](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-pubsub/lib/google/cloud/pubsub/v1/subscriber_api.rb#L187) does not match the name of the file at [`lib/google/iam/v1/iam_policy_services.rb`](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-pubsub/lib/google/iam/v1/iam_policy_services.rb), which lacks the `_pb` suffix.

I have modified the require statements locally and can confirm that doing so resolves the immediate error, although I have not yet tested the IAM methods.

/cc @swcloud

**Comment by blowmage** [comment]
Also note [this approach used in Speech](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-speech/lib/google/cloud/speech/v1beta1.rb#L16-L17), where the non-service protobufs are loaded up front so the classes are available.

**Comment by quartzmo** [comment]
I actually think the require statements are correct, and the file names should be changed to have the `_pb` suffix.

**Comment by quartzmo** [comment]
@jmuk Any guidance on this issue?

**Comment by quartzmo** [comment]
@jmuk I can easily fix this, I just want to be sure everyone knows about it, and that I do it correctly.

**Comment by jmuk** [comment]
Oops. That would be probably because I didn't regenerate iam-related files when updating to grpc-1.0 (I just missed them). File name without `_pb` suffix looks like it is pre-grpc-1.0 one. Let's regenerate them.

@Landrito is, however, working on IAM-Admin API, and he is working for some packages related to IAM protos. He might have a different idea of where those files should be.

**Comment by quartzmo** [comment]
OK, I will wait for a PR with new files. Thank you @jmuk.

**Comment by jmuk** [comment]
Created a PR -- but a different approach; since IAM can be shared among multiple APIs, we created a package called `grpc-google-iam-v1` which keeps the grpc-generated files. This PR is using it.

@landrito is actually working on a minor fix https://github.com/googleapis/api-client-staging/pull/59, so I'm going to update the version after it's merged (I was waiting but it seems not coming by today -- either way, current 0.6.8 is also working).
