### ISSUE TITLE
Do ACL calls need to support incremental backoff?

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/google-cloud-ruby#95]
We have facilities to retry some API calls by incrementally delaying the retry. This is implemented on creating/deleting buckets. Does this also need to be applied to the ACL API calls?

**Comment by blowmage** [comment]
This answer might be more obvious as part of the review by the storage team. I just don't have a great deal of knowledge on what storage API endpoints will return a backoff response.

**Comment by Capstan** [comment]
Pretty much everything should be dealt with by using some form of backoff for a 5xx or 429 response.

The problem comes when the client makes non-idempotent operations. In that case, just a dumb retry may not do what you want. For ACLs, setting an individual entry is likely to be OK. For setting the entire list, you may wish to be careful about ensuring you're editing the same metadata generation so you don't clobber someone else's ACL (or other metadata) change.

**Comment by blowmage** [comment]
All these calls are made through Google API Client now, which supports retry with incremental backoff.
