### ISSUE TITLE
Outdated usage of entries.list API request

### ISSUE THREAD

**Issue by frankyn** [GoogleCloudPlatform/google-cloud-ruby#971]
Issue: In the logging/service.rb file, an deprecated fieldName (projectIds) of [entries.list](https://cloud.google.com/logging/docs/api/ref_v2beta1/rest/v2beta1/entries/list) API is being used. 

https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/2d6c92137152d5297e91e1b5c336ed94b5ac96e7/google-cloud-logging/lib/google/cloud/logging/service.rb#L95-L109

**Comment by blowmage** [comment]
Ugh. When was this field deprecated?

It looks like `resource_names` was [added to the protobuf fields](https://github.com/GoogleCloudPlatform/google-cloud-ruby/commit/afab11003c60f13be9dede40f06d32bc85540716#diff-c4caad6baa73da990e0545a7aebdb078R28) a couple weeks ago. I take it we should `resource_names` instead of `project_ids`?

**Comment by blowmage** [comment]
@dazuma's Any input on this?  Should we add a `resources` argument to the `project#entities` method?

**Comment by frankyn** [comment]
While working with Remi, we came across it trying to figure out a different issue. Yes, that's what we understood as of now.

**Comment by blowmage** [comment]
@hxiong388 Thoughts?

**Comment by hxiong388** [comment]
According to the [doc](https://cloud.google.com/logging/docs/api/ref_v2beta1/rest/v2beta1/entries/list), resourceNames field includes the deprecated projectIds value. But since the [GAPIC API](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/82dba112a1b5202fb07c616f488cc181fd72d9f6/google-cloud-logging/lib/google/cloud/logging/v2/logging_service_v2_api.rb#L374-L376) currently requires project_ids parameter, maybe we can achieve backward compatibility by adding a new resource_names parameter to Service#list_entries, and consolidate project_ids and resource_names into one parameter:
```ruby
def list_entries projects: nil, resource_names: [], ...
  resource_names = Array(projects || @project) + resource_names
  ...
  paged_enum = logging.list_log_entries nil, resource_names: resource_names , ...
```
Propagate the same resource_names parameter to Google::Cloud::Logging::Project#entries as well.

Later whoever removes the deprecated project_ids field from GAPIC API can clean up these two Veneer APIs.

**Comment by blowmage** [comment]
When will `project_ids` be removed from the API? Also, the [documentation site that shows the field as deprecated](https://cloud.google.com/logging/docs/api/ref_v2beta1/rest/v2beta1/entries/list#body.request_body.FIELDS.project_ids) is showing the version as `v2beta1`, but Google Cloud Stackdriver Logging is using `v2`. Are the GAPIC/GRPC endpoints stable? Or will there be additional changes to the released API?

**Comment by frankyn** [comment]
I don't want to leave you hanging Mike, I have forwarded your questions and waiting on a response!

**Comment by filipjs** [comment]
Hi. We do not have a timeline yet for the field removal, but most likely that will happen in a couple of months. If you have an option to change your code to use resource_names, please do so.
Yes, we are in the process of renaming our docs from v2beta1 to v2, and there are no other changes planned. The endpoints also do not change.

**Comment by blowmage** [comment]
@filipjs If a user is using the current release of the google-cloud-logging library, and does not upgrade to a new version that uses the new field, will their client stop working? Are you removing the field from the published protobufs? Or are you removing the field from the server API?

**Comment by filipjs** [comment]
It will continue to work until it's removed from the protobuf, which means the service will stop accepting it.
